// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vfinn_design_wrapper__Syms.h"
#include "Vfinn_design_wrapper.h"
#include "Vfinn_design_wrapper___024root.h"

// FUNCTIONS
Vfinn_design_wrapper__Syms::~Vfinn_design_wrapper__Syms()
{
    delete __Vm_threadPoolp;
}

Vfinn_design_wrapper__Syms::Vfinn_design_wrapper__Syms(VerilatedContext* contextp, const char* namep,Vfinn_design_wrapper* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    , __Vm_threadPoolp{new VlThreadPool{_vm_contextp__, 3, nullptr}}
    // Setup module instances
    , TOP{this, namep}
{
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_15__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_15.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_15__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_15.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_15__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_15.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_15__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_15.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_22__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_22.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_22__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_22.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_22__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_22.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_22__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_22.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_24__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_24.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_24__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_24.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_24__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_24.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_24__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_24.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_29__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_29.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_29__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_29.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_29__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_29.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_29__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_29.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_31__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_31.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_31__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_31.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_31__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_31.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_31__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_31.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_35__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_35.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_35__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_35.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_35__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_35.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_35__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_35.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_37__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_37.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_37__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_37.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_37__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_37.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_37__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_37.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_3__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_3.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_3__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_3.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_3__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_3.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_3__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_3.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_43__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_43.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_43__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_43.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_43__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_43.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_43__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_43.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_45__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_45.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_45__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_45.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_45__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_45.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_45__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_45.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_49__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_49.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_49__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_49.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_49__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_49.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_49__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_49.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_51__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_51.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_51__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_51.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_51__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_51.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_51__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_51.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_8__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_8.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst", "xpm_fifo_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_8__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_8.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_8__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_8.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst", "xpm_memory_base_inst", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_finn_design_wrapper__finn_design_i__StreamingFIFO_rtl_8__fifo__inst__gen_fifo__xpm_fifo_axis_inst__xpm_fifo_base_inst__gen_sdpram__xpm_memory_base_inst__config_drc.configure(this, name(), "finn_design_wrapper.finn_design_i.StreamingFIFO_rtl_8.fifo.inst.gen_fifo.xpm_fifo_axis_inst.xpm_fifo_base_inst.gen_sdpram.xpm_memory_base_inst.config_drc", "config_drc", -12, VerilatedScope::SCOPE_OTHER);
}
