-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity StreamingMaxPool_hls_1_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_V_TREADY : IN STD_LOGIC;
    buf_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_ce0 : OUT STD_LOGIC;
    buf_V_we0 : OUT STD_LOGIC;
    buf_V_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_1_ce0 : OUT STD_LOGIC;
    buf_V_1_we0 : OUT STD_LOGIC;
    buf_V_1_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_1_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_2_ce0 : OUT STD_LOGIC;
    buf_V_2_we0 : OUT STD_LOGIC;
    buf_V_2_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_2_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_3_ce0 : OUT STD_LOGIC;
    buf_V_3_we0 : OUT STD_LOGIC;
    buf_V_3_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_3_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_4_ce0 : OUT STD_LOGIC;
    buf_V_4_we0 : OUT STD_LOGIC;
    buf_V_4_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_4_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_5_ce0 : OUT STD_LOGIC;
    buf_V_5_we0 : OUT STD_LOGIC;
    buf_V_5_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_5_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_6_ce0 : OUT STD_LOGIC;
    buf_V_6_we0 : OUT STD_LOGIC;
    buf_V_6_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_6_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    buf_V_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_V_7_ce0 : OUT STD_LOGIC;
    buf_V_7_we0 : OUT STD_LOGIC;
    buf_V_7_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buf_V_7_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    out_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    out_V_TVALID : OUT STD_LOGIC );
end;


architecture behav of StreamingMaxPool_hls_1_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_68 : STD_LOGIC_VECTOR (6 downto 0) := "1101000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln174_reg_246 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_246_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal icmp_ln174_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_V_TDATA_blk_n : STD_LOGIC;
    signal outpix_cast_fu_201_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal outpix_fu_58 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln174_fu_195_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_outpix_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_247 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component StreamingMaxPool_hls_1_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component StreamingMaxPool_hls_1_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    outpix_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_247)) then
                if ((icmp_ln174_fu_189_p2 = ap_const_lv1_0)) then 
                    outpix_fu_58 <= add_ln174_fu_195_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    outpix_fu_58 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                icmp_ln174_reg_246 <= icmp_ln174_fu_189_p2;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_start_int)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, out_V_TREADY, icmp_ln174_reg_246, icmp_ln174_reg_246_pp0_iter0_reg, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_start_int)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                elsif (((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and (icmp_ln174_reg_246_pp0_iter0_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or (not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;
    add_ln174_fu_195_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_outpix_1) + unsigned(ap_const_lv7_1));
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_block_state2_io_assign_proc : process(out_V_TREADY, icmp_ln174_reg_246)
    begin
                ap_block_state2_io <= ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(out_V_TREADY, icmp_ln174_reg_246)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0));
    end process;


    ap_condition_247_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_start_int)
    begin
                ap_condition_247 <= (not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_outpix_1_assign_proc : process(ap_CS_iter0_fsm_state1, outpix_fu_58, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_outpix_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_outpix_1 <= outpix_fu_58;
        end if; 
    end process;

    buf_V_1_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_1_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_1_ce0 <= ap_const_logic_1;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_1_d0 <= ap_const_lv3_0;

    buf_V_1_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_1_we0 <= ap_const_logic_1;
        else 
            buf_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_2_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_2_ce0 <= ap_const_logic_1;
        else 
            buf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_d0 <= ap_const_lv3_0;

    buf_V_2_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_2_we0 <= ap_const_logic_1;
        else 
            buf_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_3_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_3_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_3_ce0 <= ap_const_logic_1;
        else 
            buf_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_3_d0 <= ap_const_lv3_0;

    buf_V_3_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_3_we0 <= ap_const_logic_1;
        else 
            buf_V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_4_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_4_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_4_ce0 <= ap_const_logic_1;
        else 
            buf_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_4_d0 <= ap_const_lv3_0;

    buf_V_4_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_4_we0 <= ap_const_logic_1;
        else 
            buf_V_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_5_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_5_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_5_ce0 <= ap_const_logic_1;
        else 
            buf_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_5_d0 <= ap_const_lv3_0;

    buf_V_5_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_5_we0 <= ap_const_logic_1;
        else 
            buf_V_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_6_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_6_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_6_ce0 <= ap_const_logic_1;
        else 
            buf_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_6_d0 <= ap_const_lv3_0;

    buf_V_6_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_6_we0 <= ap_const_logic_1;
        else 
            buf_V_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_7_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_7_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_7_ce0 <= ap_const_logic_1;
        else 
            buf_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_7_d0 <= ap_const_lv3_0;

    buf_V_7_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_7_we0 <= ap_const_logic_1;
        else 
            buf_V_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_address0 <= outpix_cast_fu_201_p1(7 - 1 downto 0);

    buf_V_ce0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_ce0 <= ap_const_logic_1;
        else 
            buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_d0 <= ap_const_lv3_0;

    buf_V_we0_assign_proc : process(ap_CS_iter0_fsm_state1, out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2, icmp_ln174_fu_189_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))))) and (icmp_ln174_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            buf_V_we0 <= ap_const_logic_1;
        else 
            buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln174_fu_189_p2 <= "1" when (ap_sig_allocacmp_outpix_1 = ap_const_lv7_68) else "0";
    icmp_ln174_reg_246_pp0_iter0_reg <= icmp_ln174_reg_246;
    out_V_TDATA <= (((((((buf_V_7_q0 & buf_V_6_q0) & buf_V_5_q0) & buf_V_4_q0) & buf_V_3_q0) & buf_V_2_q0) & buf_V_1_q0) & buf_V_q0);

    out_V_TDATA_blk_n_assign_proc : process(out_V_TREADY, icmp_ln174_reg_246, ap_CS_iter1_fsm_state2)
    begin
        if (((icmp_ln174_reg_246 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            out_V_TDATA_blk_n <= out_V_TREADY;
        else 
            out_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_V_TVALID_assign_proc : process(out_V_TREADY, icmp_ln174_reg_246, ap_block_state2_io, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or ((icmp_ln174_reg_246 = ap_const_lv1_0) and (out_V_TREADY = ap_const_logic_0)))) and (icmp_ln174_reg_246 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            out_V_TVALID <= ap_const_logic_1;
        else 
            out_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    outpix_cast_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_outpix_1),64));
end behav;
