// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_hls_2_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        buf_V_15_load_1,
        buf_V_14_load_1,
        buf_V_13_load_1,
        buf_V_12_load_1,
        buf_V_11_load_1,
        buf_V_10_load_1,
        buf_V_9_load_1,
        buf_V_8_load_1,
        buf_V_7_load_1,
        buf_V_6_load_1,
        buf_V_5_load_1,
        buf_V_4_load_1,
        buf_V_3_load_1,
        buf_V_2_load_1,
        buf_V_1_load_1,
        buf_V_load_1,
        buf_V_15_address0,
        buf_V_15_ce0,
        buf_V_15_we0,
        buf_V_15_d0,
        zext_ln156,
        buf_V_14_address0,
        buf_V_14_ce0,
        buf_V_14_we0,
        buf_V_14_d0,
        buf_V_13_address0,
        buf_V_13_ce0,
        buf_V_13_we0,
        buf_V_13_d0,
        buf_V_12_address0,
        buf_V_12_ce0,
        buf_V_12_we0,
        buf_V_12_d0,
        buf_V_11_address0,
        buf_V_11_ce0,
        buf_V_11_we0,
        buf_V_11_d0,
        buf_V_10_address0,
        buf_V_10_ce0,
        buf_V_10_we0,
        buf_V_10_d0,
        buf_V_9_address0,
        buf_V_9_ce0,
        buf_V_9_we0,
        buf_V_9_d0,
        buf_V_8_address0,
        buf_V_8_ce0,
        buf_V_8_we0,
        buf_V_8_d0,
        buf_V_7_address0,
        buf_V_7_ce0,
        buf_V_7_we0,
        buf_V_7_d0,
        buf_V_6_address0,
        buf_V_6_ce0,
        buf_V_6_we0,
        buf_V_6_d0,
        buf_V_5_address0,
        buf_V_5_ce0,
        buf_V_5_we0,
        buf_V_5_d0,
        buf_V_4_address0,
        buf_V_4_ce0,
        buf_V_4_we0,
        buf_V_4_d0,
        buf_V_3_address0,
        buf_V_3_ce0,
        buf_V_3_we0,
        buf_V_3_d0,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_we0,
        buf_V_2_d0,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_we0,
        buf_V_1_d0,
        buf_V_address0,
        buf_V_ce0,
        buf_V_we0,
        buf_V_d0,
        in0_V_TDATA,
        in0_V_TREADY
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input  [2:0] buf_V_15_load_1;
input  [2:0] buf_V_14_load_1;
input  [2:0] buf_V_13_load_1;
input  [2:0] buf_V_12_load_1;
input  [2:0] buf_V_11_load_1;
input  [2:0] buf_V_10_load_1;
input  [2:0] buf_V_9_load_1;
input  [2:0] buf_V_8_load_1;
input  [2:0] buf_V_7_load_1;
input  [2:0] buf_V_6_load_1;
input  [2:0] buf_V_5_load_1;
input  [2:0] buf_V_4_load_1;
input  [2:0] buf_V_3_load_1;
input  [2:0] buf_V_2_load_1;
input  [2:0] buf_V_1_load_1;
input  [2:0] buf_V_load_1;
output  [5:0] buf_V_15_address0;
output   buf_V_15_ce0;
output   buf_V_15_we0;
output  [2:0] buf_V_15_d0;
input  [5:0] zext_ln156;
output  [5:0] buf_V_14_address0;
output   buf_V_14_ce0;
output   buf_V_14_we0;
output  [2:0] buf_V_14_d0;
output  [5:0] buf_V_13_address0;
output   buf_V_13_ce0;
output   buf_V_13_we0;
output  [2:0] buf_V_13_d0;
output  [5:0] buf_V_12_address0;
output   buf_V_12_ce0;
output   buf_V_12_we0;
output  [2:0] buf_V_12_d0;
output  [5:0] buf_V_11_address0;
output   buf_V_11_ce0;
output   buf_V_11_we0;
output  [2:0] buf_V_11_d0;
output  [5:0] buf_V_10_address0;
output   buf_V_10_ce0;
output   buf_V_10_we0;
output  [2:0] buf_V_10_d0;
output  [5:0] buf_V_9_address0;
output   buf_V_9_ce0;
output   buf_V_9_we0;
output  [2:0] buf_V_9_d0;
output  [5:0] buf_V_8_address0;
output   buf_V_8_ce0;
output   buf_V_8_we0;
output  [2:0] buf_V_8_d0;
output  [5:0] buf_V_7_address0;
output   buf_V_7_ce0;
output   buf_V_7_we0;
output  [2:0] buf_V_7_d0;
output  [5:0] buf_V_6_address0;
output   buf_V_6_ce0;
output   buf_V_6_we0;
output  [2:0] buf_V_6_d0;
output  [5:0] buf_V_5_address0;
output   buf_V_5_ce0;
output   buf_V_5_we0;
output  [2:0] buf_V_5_d0;
output  [5:0] buf_V_4_address0;
output   buf_V_4_ce0;
output   buf_V_4_we0;
output  [2:0] buf_V_4_d0;
output  [5:0] buf_V_3_address0;
output   buf_V_3_ce0;
output   buf_V_3_we0;
output  [2:0] buf_V_3_d0;
output  [5:0] buf_V_2_address0;
output   buf_V_2_ce0;
output   buf_V_2_we0;
output  [2:0] buf_V_2_d0;
output  [5:0] buf_V_1_address0;
output   buf_V_1_ce0;
output   buf_V_1_we0;
output  [2:0] buf_V_1_d0;
output  [5:0] buf_V_address0;
output   buf_V_ce0;
output   buf_V_we0;
output  [2:0] buf_V_d0;
input  [47:0] in0_V_TDATA;
output   in0_V_TREADY;

reg ap_idle;
reg buf_V_15_ce0;
reg buf_V_15_we0;
reg buf_V_14_ce0;
reg buf_V_14_we0;
reg buf_V_13_ce0;
reg buf_V_13_we0;
reg buf_V_12_ce0;
reg buf_V_12_we0;
reg buf_V_11_ce0;
reg buf_V_11_we0;
reg buf_V_10_ce0;
reg buf_V_10_we0;
reg buf_V_9_ce0;
reg buf_V_9_we0;
reg buf_V_8_ce0;
reg buf_V_8_we0;
reg buf_V_7_ce0;
reg buf_V_7_we0;
reg buf_V_6_ce0;
reg buf_V_6_we0;
reg buf_V_5_ce0;
reg buf_V_5_we0;
reg buf_V_4_ce0;
reg buf_V_4_we0;
reg buf_V_3_ce0;
reg buf_V_3_we0;
reg buf_V_2_ce0;
reg buf_V_2_we0;
reg buf_V_1_ce0;
reg buf_V_1_we0;
reg buf_V_ce0;
reg buf_V_we0;
reg in0_V_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln158_fu_662_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
wire   [63:0] zext_ln156_cast_fu_554_p1;
reg   [1:0] kx_fu_170;
wire   [1:0] kx_2_fu_668_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_kx_1;
reg   [2:0] oldMax_V_fu_174;
wire   [2:0] select_ln167_fu_732_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_load;
reg   [2:0] oldMax_V_1_fu_178;
wire   [2:0] select_ln167_1_fu_757_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_1_load;
reg   [2:0] oldMax_V_2_fu_182;
wire   [2:0] select_ln167_2_fu_782_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_2_load;
reg   [2:0] oldMax_V_3_fu_186;
wire   [2:0] select_ln167_3_fu_807_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_3_load;
reg   [2:0] oldMax_V_4_fu_190;
wire   [2:0] select_ln167_4_fu_832_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_4_load;
reg   [2:0] oldMax_V_5_fu_194;
wire   [2:0] select_ln167_5_fu_857_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_5_load;
reg   [2:0] oldMax_V_6_fu_198;
wire   [2:0] select_ln167_6_fu_882_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_6_load;
reg   [2:0] oldMax_V_7_fu_202;
wire   [2:0] select_ln167_7_fu_907_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_7_load;
reg   [2:0] oldMax_V_8_fu_206;
wire   [2:0] select_ln167_8_fu_932_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_8_load;
reg   [2:0] oldMax_V_9_fu_210;
wire   [2:0] select_ln167_9_fu_957_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_9_load;
reg   [2:0] oldMax_V_10_fu_214;
wire   [2:0] select_ln167_10_fu_982_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_10_load;
reg   [2:0] oldMax_V_11_fu_218;
wire   [2:0] select_ln167_11_fu_1007_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_11_load;
reg   [2:0] oldMax_V_12_fu_222;
wire   [2:0] select_ln167_12_fu_1032_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_12_load;
reg   [2:0] oldMax_V_13_fu_226;
wire   [2:0] select_ln167_13_fu_1057_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_13_load;
reg   [2:0] oldMax_V_14_fu_230;
wire   [2:0] select_ln167_14_fu_1082_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_14_load;
reg   [2:0] oldMax_V_15_fu_234;
wire   [2:0] select_ln167_15_fu_1107_p3;
reg   [2:0] ap_sig_allocacmp_oldMax_V_15_load;
wire   [0:0] icmp_ln158_1_fu_1116_p2;
wire   [2:0] channeldata_V_fu_722_p1;
wire   [0:0] icmp_ln1035_fu_726_p2;
wire   [2:0] channeldata_V_1_fu_741_p4;
wire   [0:0] icmp_ln1035_1_fu_751_p2;
wire   [2:0] channeldata_V_2_fu_766_p4;
wire   [0:0] icmp_ln1035_2_fu_776_p2;
wire   [2:0] channeldata_V_3_fu_791_p4;
wire   [0:0] icmp_ln1035_3_fu_801_p2;
wire   [2:0] channeldata_V_4_fu_816_p4;
wire   [0:0] icmp_ln1035_4_fu_826_p2;
wire   [2:0] channeldata_V_5_fu_841_p4;
wire   [0:0] icmp_ln1035_5_fu_851_p2;
wire   [2:0] channeldata_V_6_fu_866_p4;
wire   [0:0] icmp_ln1035_6_fu_876_p2;
wire   [2:0] channeldata_V_7_fu_891_p4;
wire   [0:0] icmp_ln1035_7_fu_901_p2;
wire   [2:0] channeldata_V_8_fu_916_p4;
wire   [0:0] icmp_ln1035_8_fu_926_p2;
wire   [2:0] channeldata_V_9_fu_941_p4;
wire   [0:0] icmp_ln1035_9_fu_951_p2;
wire   [2:0] channeldata_V_10_fu_966_p4;
wire   [0:0] icmp_ln1035_10_fu_976_p2;
wire   [2:0] channeldata_V_11_fu_991_p4;
wire   [0:0] icmp_ln1035_11_fu_1001_p2;
wire   [2:0] channeldata_V_12_fu_1016_p4;
wire   [0:0] icmp_ln1035_12_fu_1026_p2;
wire   [2:0] channeldata_V_13_fu_1041_p4;
wire   [0:0] icmp_ln1035_13_fu_1051_p2;
wire   [2:0] channeldata_V_14_fu_1066_p4;
wire   [0:0] icmp_ln1035_14_fu_1076_p2;
wire   [2:0] channeldata_V_15_fu_1091_p4;
wire   [0:0] icmp_ln1035_15_fu_1101_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_573;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

StreamingMaxPool_hls_2_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            kx_fu_170 <= kx_2_fu_668_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kx_fu_170 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_10_fu_214 <= select_ln167_10_fu_982_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_10_fu_214 <= buf_V_10_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_11_fu_218 <= select_ln167_11_fu_1007_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_11_fu_218 <= buf_V_11_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_12_fu_222 <= select_ln167_12_fu_1032_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_12_fu_222 <= buf_V_12_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_13_fu_226 <= select_ln167_13_fu_1057_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_13_fu_226 <= buf_V_13_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_14_fu_230 <= select_ln167_14_fu_1082_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_14_fu_230 <= buf_V_14_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_15_fu_234 <= select_ln167_15_fu_1107_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_15_fu_234 <= buf_V_15_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_1_fu_178 <= select_ln167_1_fu_757_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_1_fu_178 <= buf_V_1_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_2_fu_182 <= select_ln167_2_fu_782_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_2_fu_182 <= buf_V_2_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_3_fu_186 <= select_ln167_3_fu_807_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_3_fu_186 <= buf_V_3_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_4_fu_190 <= select_ln167_4_fu_832_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_4_fu_190 <= buf_V_4_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_5_fu_194 <= select_ln167_5_fu_857_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_5_fu_194 <= buf_V_5_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_6_fu_198 <= select_ln167_6_fu_882_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_6_fu_198 <= buf_V_6_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_7_fu_202 <= select_ln167_7_fu_907_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_7_fu_202 <= buf_V_7_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_8_fu_206 <= select_ln167_8_fu_932_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_8_fu_206 <= buf_V_8_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_9_fu_210 <= select_ln167_9_fu_957_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_9_fu_210 <= buf_V_9_load_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_573)) begin
        if ((icmp_ln158_fu_662_p2 == 1'd0)) begin
            oldMax_V_fu_174 <= select_ln167_fu_732_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oldMax_V_fu_174 <= buf_V_load_1;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_fu_662_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_kx_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_kx_1 = kx_fu_170;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_10_load = buf_V_10_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_10_load = oldMax_V_10_fu_214;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_11_load = buf_V_11_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_11_load = oldMax_V_11_fu_218;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_12_load = buf_V_12_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_12_load = oldMax_V_12_fu_222;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_13_load = buf_V_13_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_13_load = oldMax_V_13_fu_226;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_14_load = buf_V_14_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_14_load = oldMax_V_14_fu_230;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_15_load = buf_V_15_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_15_load = oldMax_V_15_fu_234;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_1_load = buf_V_1_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_1_load = oldMax_V_1_fu_178;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_2_load = buf_V_2_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_2_load = oldMax_V_2_fu_182;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_3_load = buf_V_3_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_3_load = oldMax_V_3_fu_186;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_4_load = buf_V_4_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_4_load = oldMax_V_4_fu_190;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_5_load = buf_V_5_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_5_load = oldMax_V_5_fu_194;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_6_load = buf_V_6_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_6_load = oldMax_V_6_fu_198;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_7_load = buf_V_7_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_7_load = oldMax_V_7_fu_202;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_8_load = buf_V_8_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_8_load = oldMax_V_8_fu_206;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_9_load = buf_V_9_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_9_load = oldMax_V_9_fu_210;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oldMax_V_load = buf_V_load_1;
    end else begin
        ap_sig_allocacmp_oldMax_V_load = oldMax_V_fu_174;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_10_ce0 = 1'b1;
    end else begin
        buf_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_10_we0 = 1'b1;
    end else begin
        buf_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_11_ce0 = 1'b1;
    end else begin
        buf_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_11_we0 = 1'b1;
    end else begin
        buf_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_12_ce0 = 1'b1;
    end else begin
        buf_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_12_we0 = 1'b1;
    end else begin
        buf_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_13_ce0 = 1'b1;
    end else begin
        buf_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_13_we0 = 1'b1;
    end else begin
        buf_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_14_ce0 = 1'b1;
    end else begin
        buf_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_14_we0 = 1'b1;
    end else begin
        buf_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_15_ce0 = 1'b1;
    end else begin
        buf_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_15_we0 = 1'b1;
    end else begin
        buf_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_1_we0 = 1'b1;
    end else begin
        buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_2_we0 = 1'b1;
    end else begin
        buf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_3_ce0 = 1'b1;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_3_we0 = 1'b1;
    end else begin
        buf_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_4_ce0 = 1'b1;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_4_we0 = 1'b1;
    end else begin
        buf_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_5_ce0 = 1'b1;
    end else begin
        buf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_5_we0 = 1'b1;
    end else begin
        buf_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_6_ce0 = 1'b1;
    end else begin
        buf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_6_we0 = 1'b1;
    end else begin
        buf_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_7_ce0 = 1'b1;
    end else begin
        buf_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_7_we0 = 1'b1;
    end else begin
        buf_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_8_ce0 = 1'b1;
    end else begin
        buf_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_8_we0 = 1'b1;
    end else begin
        buf_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_9_ce0 = 1'b1;
    end else begin
        buf_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_9_we0 = 1'b1;
    end else begin
        buf_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_1_fu_1116_p2 == 1'd1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_V_we0 = 1'b1;
    end else begin
        buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (icmp_ln158_fu_662_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_573 = (~((ap_start_int == 1'b0) | ((icmp_ln158_fu_662_p2 == 1'd0) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buf_V_10_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_10_d0 = ((icmp_ln1035_10_fu_976_p2[0:0] == 1'b1) ? channeldata_V_10_fu_966_p4 : ap_sig_allocacmp_oldMax_V_10_load);

assign buf_V_11_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_11_d0 = ((icmp_ln1035_11_fu_1001_p2[0:0] == 1'b1) ? channeldata_V_11_fu_991_p4 : ap_sig_allocacmp_oldMax_V_11_load);

assign buf_V_12_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_12_d0 = ((icmp_ln1035_12_fu_1026_p2[0:0] == 1'b1) ? channeldata_V_12_fu_1016_p4 : ap_sig_allocacmp_oldMax_V_12_load);

assign buf_V_13_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_13_d0 = ((icmp_ln1035_13_fu_1051_p2[0:0] == 1'b1) ? channeldata_V_13_fu_1041_p4 : ap_sig_allocacmp_oldMax_V_13_load);

assign buf_V_14_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_14_d0 = ((icmp_ln1035_14_fu_1076_p2[0:0] == 1'b1) ? channeldata_V_14_fu_1066_p4 : ap_sig_allocacmp_oldMax_V_14_load);

assign buf_V_15_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_15_d0 = ((icmp_ln1035_15_fu_1101_p2[0:0] == 1'b1) ? channeldata_V_15_fu_1091_p4 : ap_sig_allocacmp_oldMax_V_15_load);

assign buf_V_1_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_1_d0 = ((icmp_ln1035_1_fu_751_p2[0:0] == 1'b1) ? channeldata_V_1_fu_741_p4 : ap_sig_allocacmp_oldMax_V_1_load);

assign buf_V_2_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_2_d0 = ((icmp_ln1035_2_fu_776_p2[0:0] == 1'b1) ? channeldata_V_2_fu_766_p4 : ap_sig_allocacmp_oldMax_V_2_load);

assign buf_V_3_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_3_d0 = ((icmp_ln1035_3_fu_801_p2[0:0] == 1'b1) ? channeldata_V_3_fu_791_p4 : ap_sig_allocacmp_oldMax_V_3_load);

assign buf_V_4_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_4_d0 = ((icmp_ln1035_4_fu_826_p2[0:0] == 1'b1) ? channeldata_V_4_fu_816_p4 : ap_sig_allocacmp_oldMax_V_4_load);

assign buf_V_5_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_5_d0 = ((icmp_ln1035_5_fu_851_p2[0:0] == 1'b1) ? channeldata_V_5_fu_841_p4 : ap_sig_allocacmp_oldMax_V_5_load);

assign buf_V_6_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_6_d0 = ((icmp_ln1035_6_fu_876_p2[0:0] == 1'b1) ? channeldata_V_6_fu_866_p4 : ap_sig_allocacmp_oldMax_V_6_load);

assign buf_V_7_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_7_d0 = ((icmp_ln1035_7_fu_901_p2[0:0] == 1'b1) ? channeldata_V_7_fu_891_p4 : ap_sig_allocacmp_oldMax_V_7_load);

assign buf_V_8_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_8_d0 = ((icmp_ln1035_8_fu_926_p2[0:0] == 1'b1) ? channeldata_V_8_fu_916_p4 : ap_sig_allocacmp_oldMax_V_8_load);

assign buf_V_9_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_9_d0 = ((icmp_ln1035_9_fu_951_p2[0:0] == 1'b1) ? channeldata_V_9_fu_941_p4 : ap_sig_allocacmp_oldMax_V_9_load);

assign buf_V_address0 = zext_ln156_cast_fu_554_p1;

assign buf_V_d0 = ((icmp_ln1035_fu_726_p2[0:0] == 1'b1) ? channeldata_V_fu_722_p1 : ap_sig_allocacmp_oldMax_V_load);

assign channeldata_V_10_fu_966_p4 = {{in0_V_TDATA[32:30]}};

assign channeldata_V_11_fu_991_p4 = {{in0_V_TDATA[35:33]}};

assign channeldata_V_12_fu_1016_p4 = {{in0_V_TDATA[38:36]}};

assign channeldata_V_13_fu_1041_p4 = {{in0_V_TDATA[41:39]}};

assign channeldata_V_14_fu_1066_p4 = {{in0_V_TDATA[44:42]}};

assign channeldata_V_15_fu_1091_p4 = {{in0_V_TDATA[47:45]}};

assign channeldata_V_1_fu_741_p4 = {{in0_V_TDATA[5:3]}};

assign channeldata_V_2_fu_766_p4 = {{in0_V_TDATA[8:6]}};

assign channeldata_V_3_fu_791_p4 = {{in0_V_TDATA[11:9]}};

assign channeldata_V_4_fu_816_p4 = {{in0_V_TDATA[14:12]}};

assign channeldata_V_5_fu_841_p4 = {{in0_V_TDATA[17:15]}};

assign channeldata_V_6_fu_866_p4 = {{in0_V_TDATA[20:18]}};

assign channeldata_V_7_fu_891_p4 = {{in0_V_TDATA[23:21]}};

assign channeldata_V_8_fu_916_p4 = {{in0_V_TDATA[26:24]}};

assign channeldata_V_9_fu_941_p4 = {{in0_V_TDATA[29:27]}};

assign channeldata_V_fu_722_p1 = in0_V_TDATA[2:0];

assign icmp_ln1035_10_fu_976_p2 = ((channeldata_V_10_fu_966_p4 > ap_sig_allocacmp_oldMax_V_10_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_11_fu_1001_p2 = ((channeldata_V_11_fu_991_p4 > ap_sig_allocacmp_oldMax_V_11_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_12_fu_1026_p2 = ((channeldata_V_12_fu_1016_p4 > ap_sig_allocacmp_oldMax_V_12_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_13_fu_1051_p2 = ((channeldata_V_13_fu_1041_p4 > ap_sig_allocacmp_oldMax_V_13_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_14_fu_1076_p2 = ((channeldata_V_14_fu_1066_p4 > ap_sig_allocacmp_oldMax_V_14_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_15_fu_1101_p2 = ((channeldata_V_15_fu_1091_p4 > ap_sig_allocacmp_oldMax_V_15_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_751_p2 = ((channeldata_V_1_fu_741_p4 > ap_sig_allocacmp_oldMax_V_1_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_2_fu_776_p2 = ((channeldata_V_2_fu_766_p4 > ap_sig_allocacmp_oldMax_V_2_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_3_fu_801_p2 = ((channeldata_V_3_fu_791_p4 > ap_sig_allocacmp_oldMax_V_3_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_4_fu_826_p2 = ((channeldata_V_4_fu_816_p4 > ap_sig_allocacmp_oldMax_V_4_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_5_fu_851_p2 = ((channeldata_V_5_fu_841_p4 > ap_sig_allocacmp_oldMax_V_5_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_6_fu_876_p2 = ((channeldata_V_6_fu_866_p4 > ap_sig_allocacmp_oldMax_V_6_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_7_fu_901_p2 = ((channeldata_V_7_fu_891_p4 > ap_sig_allocacmp_oldMax_V_7_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_8_fu_926_p2 = ((channeldata_V_8_fu_916_p4 > ap_sig_allocacmp_oldMax_V_8_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_9_fu_951_p2 = ((channeldata_V_9_fu_941_p4 > ap_sig_allocacmp_oldMax_V_9_load) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_726_p2 = ((channeldata_V_fu_722_p1 > ap_sig_allocacmp_oldMax_V_load) ? 1'b1 : 1'b0);

assign icmp_ln158_1_fu_1116_p2 = ((kx_2_fu_668_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_662_p2 = ((ap_sig_allocacmp_kx_1 == 2'd2) ? 1'b1 : 1'b0);

assign kx_2_fu_668_p2 = (ap_sig_allocacmp_kx_1 + 2'd1);

assign select_ln167_10_fu_982_p3 = ((icmp_ln1035_10_fu_976_p2[0:0] == 1'b1) ? channeldata_V_10_fu_966_p4 : ap_sig_allocacmp_oldMax_V_10_load);

assign select_ln167_11_fu_1007_p3 = ((icmp_ln1035_11_fu_1001_p2[0:0] == 1'b1) ? channeldata_V_11_fu_991_p4 : ap_sig_allocacmp_oldMax_V_11_load);

assign select_ln167_12_fu_1032_p3 = ((icmp_ln1035_12_fu_1026_p2[0:0] == 1'b1) ? channeldata_V_12_fu_1016_p4 : ap_sig_allocacmp_oldMax_V_12_load);

assign select_ln167_13_fu_1057_p3 = ((icmp_ln1035_13_fu_1051_p2[0:0] == 1'b1) ? channeldata_V_13_fu_1041_p4 : ap_sig_allocacmp_oldMax_V_13_load);

assign select_ln167_14_fu_1082_p3 = ((icmp_ln1035_14_fu_1076_p2[0:0] == 1'b1) ? channeldata_V_14_fu_1066_p4 : ap_sig_allocacmp_oldMax_V_14_load);

assign select_ln167_15_fu_1107_p3 = ((icmp_ln1035_15_fu_1101_p2[0:0] == 1'b1) ? channeldata_V_15_fu_1091_p4 : ap_sig_allocacmp_oldMax_V_15_load);

assign select_ln167_1_fu_757_p3 = ((icmp_ln1035_1_fu_751_p2[0:0] == 1'b1) ? channeldata_V_1_fu_741_p4 : ap_sig_allocacmp_oldMax_V_1_load);

assign select_ln167_2_fu_782_p3 = ((icmp_ln1035_2_fu_776_p2[0:0] == 1'b1) ? channeldata_V_2_fu_766_p4 : ap_sig_allocacmp_oldMax_V_2_load);

assign select_ln167_3_fu_807_p3 = ((icmp_ln1035_3_fu_801_p2[0:0] == 1'b1) ? channeldata_V_3_fu_791_p4 : ap_sig_allocacmp_oldMax_V_3_load);

assign select_ln167_4_fu_832_p3 = ((icmp_ln1035_4_fu_826_p2[0:0] == 1'b1) ? channeldata_V_4_fu_816_p4 : ap_sig_allocacmp_oldMax_V_4_load);

assign select_ln167_5_fu_857_p3 = ((icmp_ln1035_5_fu_851_p2[0:0] == 1'b1) ? channeldata_V_5_fu_841_p4 : ap_sig_allocacmp_oldMax_V_5_load);

assign select_ln167_6_fu_882_p3 = ((icmp_ln1035_6_fu_876_p2[0:0] == 1'b1) ? channeldata_V_6_fu_866_p4 : ap_sig_allocacmp_oldMax_V_6_load);

assign select_ln167_7_fu_907_p3 = ((icmp_ln1035_7_fu_901_p2[0:0] == 1'b1) ? channeldata_V_7_fu_891_p4 : ap_sig_allocacmp_oldMax_V_7_load);

assign select_ln167_8_fu_932_p3 = ((icmp_ln1035_8_fu_926_p2[0:0] == 1'b1) ? channeldata_V_8_fu_916_p4 : ap_sig_allocacmp_oldMax_V_8_load);

assign select_ln167_9_fu_957_p3 = ((icmp_ln1035_9_fu_951_p2[0:0] == 1'b1) ? channeldata_V_9_fu_941_p4 : ap_sig_allocacmp_oldMax_V_9_load);

assign select_ln167_fu_732_p3 = ((icmp_ln1035_fu_726_p2[0:0] == 1'b1) ? channeldata_V_fu_722_p1 : ap_sig_allocacmp_oldMax_V_load);

assign zext_ln156_cast_fu_554_p1 = zext_ln156;

endmodule //StreamingMaxPool_hls_2_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6
