// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TDATA,
        in0_V_TVALID,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [47:0] in0_V_TDATA;
input   in0_V_TVALID;
output   in0_V_TREADY;
output  [47:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in0_V_TREADY;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] yp_2_fu_449_p2;
reg   [5:0] yp_2_reg_521;
wire    ap_CS_fsm_state3;
wire   [6:0] add_ln155_fu_461_p2;
reg   [6:0] add_ln155_reg_529;
wire    ap_CS_fsm_state4;
wire   [5:0] select_ln155_fu_473_p3;
reg   [5:0] select_ln155_reg_534;
wire   [0:0] icmp_ln155_fu_455_p2;
wire   [5:0] add_ln156_fu_501_p2;
reg   [5:0] add_ln156_reg_619;
wire   [2:0] buf_V_q0;
reg   [2:0] buf_V_load_reg_624;
wire    ap_CS_fsm_state5;
wire   [2:0] buf_V_1_q0;
reg   [2:0] buf_V_1_load_reg_629;
wire   [2:0] buf_V_2_q0;
reg   [2:0] buf_V_2_load_reg_634;
wire   [2:0] buf_V_3_q0;
reg   [2:0] buf_V_3_load_reg_639;
wire   [2:0] buf_V_4_q0;
reg   [2:0] buf_V_4_load_reg_644;
wire   [2:0] buf_V_5_q0;
reg   [2:0] buf_V_5_load_reg_649;
wire   [2:0] buf_V_6_q0;
reg   [2:0] buf_V_6_load_reg_654;
wire   [2:0] buf_V_7_q0;
reg   [2:0] buf_V_7_load_reg_659;
wire   [2:0] buf_V_8_q0;
reg   [2:0] buf_V_8_load_reg_664;
wire   [2:0] buf_V_9_q0;
reg   [2:0] buf_V_9_load_reg_669;
wire   [2:0] buf_V_10_q0;
reg   [2:0] buf_V_10_load_reg_674;
wire   [2:0] buf_V_11_q0;
reg   [2:0] buf_V_11_load_reg_679;
wire   [2:0] buf_V_12_q0;
reg   [2:0] buf_V_12_load_reg_684;
wire   [2:0] buf_V_13_q0;
reg   [2:0] buf_V_13_load_reg_689;
wire   [2:0] buf_V_14_q0;
reg   [2:0] buf_V_14_load_reg_694;
wire   [2:0] buf_V_15_q0;
reg   [2:0] buf_V_15_load_reg_699;
reg   [5:0] buf_V_address0;
reg    buf_V_ce0;
reg    buf_V_we0;
reg   [2:0] buf_V_d0;
reg   [5:0] buf_V_1_address0;
reg    buf_V_1_ce0;
reg    buf_V_1_we0;
reg   [2:0] buf_V_1_d0;
reg   [5:0] buf_V_2_address0;
reg    buf_V_2_ce0;
reg    buf_V_2_we0;
reg   [2:0] buf_V_2_d0;
reg   [5:0] buf_V_3_address0;
reg    buf_V_3_ce0;
reg    buf_V_3_we0;
reg   [2:0] buf_V_3_d0;
reg   [5:0] buf_V_4_address0;
reg    buf_V_4_ce0;
reg    buf_V_4_we0;
reg   [2:0] buf_V_4_d0;
reg   [5:0] buf_V_5_address0;
reg    buf_V_5_ce0;
reg    buf_V_5_we0;
reg   [2:0] buf_V_5_d0;
reg   [5:0] buf_V_6_address0;
reg    buf_V_6_ce0;
reg    buf_V_6_we0;
reg   [2:0] buf_V_6_d0;
reg   [5:0] buf_V_7_address0;
reg    buf_V_7_ce0;
reg    buf_V_7_we0;
reg   [2:0] buf_V_7_d0;
reg   [5:0] buf_V_8_address0;
reg    buf_V_8_ce0;
reg    buf_V_8_we0;
reg   [2:0] buf_V_8_d0;
reg   [5:0] buf_V_9_address0;
reg    buf_V_9_ce0;
reg    buf_V_9_we0;
reg   [2:0] buf_V_9_d0;
reg   [5:0] buf_V_10_address0;
reg    buf_V_10_ce0;
reg    buf_V_10_we0;
reg   [2:0] buf_V_10_d0;
reg   [5:0] buf_V_11_address0;
reg    buf_V_11_ce0;
reg    buf_V_11_we0;
reg   [2:0] buf_V_11_d0;
reg   [5:0] buf_V_12_address0;
reg    buf_V_12_ce0;
reg    buf_V_12_we0;
reg   [2:0] buf_V_12_d0;
reg   [5:0] buf_V_13_address0;
reg    buf_V_13_ce0;
reg    buf_V_13_we0;
reg   [2:0] buf_V_13_d0;
reg   [5:0] buf_V_14_address0;
reg    buf_V_14_ce0;
reg    buf_V_14_we0;
reg   [2:0] buf_V_14_d0;
reg   [5:0] buf_V_15_address0;
reg    buf_V_15_ce0;
reg    buf_V_15_we0;
reg   [2:0] buf_V_15_d0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_done;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_idle;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_ready;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_d0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_done;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_idle;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_ready;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TREADY;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_d0;
wire   [47:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TDATA;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TVALID;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_done;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_idle;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_ready;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_d0;
wire   [5:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_address0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_ce0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_we0;
wire   [2:0] grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_d0;
wire    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_in0_V_TREADY;
reg   [6:0] indvar_flatten_reg_316;
wire   [0:0] icmp_ln154_fu_443_p2;
wire    ap_CS_fsm_state7;
reg   [5:0] xp_reg_327;
reg    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln156_fu_481_p1;
reg   [5:0] yp_fu_56;
wire   [0:0] icmp_ln156_fu_467_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start_reg = 1'b0;
#0 grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start_reg = 1'b0;
#0 grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start_reg = 1'b0;
end

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_address0),
    .ce0(buf_V_ce0),
    .we0(buf_V_we0),
    .d0(buf_V_d0),
    .q0(buf_V_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .we0(buf_V_1_we0),
    .d0(buf_V_1_d0),
    .q0(buf_V_1_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_2_address0),
    .ce0(buf_V_2_ce0),
    .we0(buf_V_2_we0),
    .d0(buf_V_2_d0),
    .q0(buf_V_2_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_3_address0),
    .ce0(buf_V_3_ce0),
    .we0(buf_V_3_we0),
    .d0(buf_V_3_d0),
    .q0(buf_V_3_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_4_address0),
    .ce0(buf_V_4_ce0),
    .we0(buf_V_4_we0),
    .d0(buf_V_4_d0),
    .q0(buf_V_4_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_5_address0),
    .ce0(buf_V_5_ce0),
    .we0(buf_V_5_we0),
    .d0(buf_V_5_d0),
    .q0(buf_V_5_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_6_address0),
    .ce0(buf_V_6_ce0),
    .we0(buf_V_6_we0),
    .d0(buf_V_6_d0),
    .q0(buf_V_6_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_7_address0),
    .ce0(buf_V_7_ce0),
    .we0(buf_V_7_we0),
    .d0(buf_V_7_d0),
    .q0(buf_V_7_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_8_address0),
    .ce0(buf_V_8_ce0),
    .we0(buf_V_8_we0),
    .d0(buf_V_8_d0),
    .q0(buf_V_8_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_9_address0),
    .ce0(buf_V_9_ce0),
    .we0(buf_V_9_we0),
    .d0(buf_V_9_d0),
    .q0(buf_V_9_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_10_address0),
    .ce0(buf_V_10_ce0),
    .we0(buf_V_10_we0),
    .d0(buf_V_10_d0),
    .q0(buf_V_10_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_11_address0),
    .ce0(buf_V_11_ce0),
    .we0(buf_V_11_we0),
    .d0(buf_V_11_d0),
    .q0(buf_V_11_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_12_address0),
    .ce0(buf_V_12_ce0),
    .we0(buf_V_12_we0),
    .d0(buf_V_12_d0),
    .q0(buf_V_12_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_13_address0),
    .ce0(buf_V_13_ce0),
    .we0(buf_V_13_we0),
    .d0(buf_V_13_d0),
    .q0(buf_V_13_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_14_address0),
    .ce0(buf_V_14_ce0),
    .we0(buf_V_14_we0),
    .d0(buf_V_14_d0),
    .q0(buf_V_14_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s_buf_V_RAM_AUTO_1R1W #(
    .DataWidth( 3 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
buf_V_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_15_address0),
    .ce0(buf_V_15_ce0),
    .we0(buf_V_15_we0),
    .d0(buf_V_15_d0),
    .q0(buf_V_15_q0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1 grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start),
    .ap_done(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_done),
    .ap_idle(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_idle),
    .ap_ready(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_ready),
    .buf_V_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_address0),
    .buf_V_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_ce0),
    .buf_V_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_we0),
    .buf_V_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_d0),
    .buf_V_1_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_address0),
    .buf_V_1_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_ce0),
    .buf_V_1_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_we0),
    .buf_V_1_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_d0),
    .buf_V_2_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_address0),
    .buf_V_2_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_ce0),
    .buf_V_2_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_we0),
    .buf_V_2_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_d0),
    .buf_V_3_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_address0),
    .buf_V_3_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_ce0),
    .buf_V_3_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_we0),
    .buf_V_3_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_d0),
    .buf_V_4_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_address0),
    .buf_V_4_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_ce0),
    .buf_V_4_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_we0),
    .buf_V_4_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_d0),
    .buf_V_5_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_address0),
    .buf_V_5_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_ce0),
    .buf_V_5_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_we0),
    .buf_V_5_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_d0),
    .buf_V_6_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_address0),
    .buf_V_6_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_ce0),
    .buf_V_6_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_we0),
    .buf_V_6_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_d0),
    .buf_V_7_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_address0),
    .buf_V_7_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_ce0),
    .buf_V_7_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_we0),
    .buf_V_7_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_d0),
    .buf_V_8_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_address0),
    .buf_V_8_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_ce0),
    .buf_V_8_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_we0),
    .buf_V_8_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_d0),
    .buf_V_9_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_address0),
    .buf_V_9_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_ce0),
    .buf_V_9_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_we0),
    .buf_V_9_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_d0),
    .buf_V_10_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_address0),
    .buf_V_10_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_ce0),
    .buf_V_10_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_we0),
    .buf_V_10_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_d0),
    .buf_V_11_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_address0),
    .buf_V_11_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_ce0),
    .buf_V_11_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_we0),
    .buf_V_11_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_d0),
    .buf_V_12_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_address0),
    .buf_V_12_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_ce0),
    .buf_V_12_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_we0),
    .buf_V_12_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_d0),
    .buf_V_13_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_address0),
    .buf_V_13_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_ce0),
    .buf_V_13_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_we0),
    .buf_V_13_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_d0),
    .buf_V_14_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_address0),
    .buf_V_14_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_ce0),
    .buf_V_14_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_we0),
    .buf_V_14_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_d0),
    .buf_V_15_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_address0),
    .buf_V_15_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_ce0),
    .buf_V_15_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_we0),
    .buf_V_15_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_d0)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8 grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start),
    .ap_done(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_done),
    .ap_idle(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_idle),
    .ap_ready(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_ready),
    .out_V_TREADY(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TREADY),
    .buf_V_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_address0),
    .buf_V_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_ce0),
    .buf_V_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_we0),
    .buf_V_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_d0),
    .buf_V_q0(buf_V_q0),
    .buf_V_1_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_address0),
    .buf_V_1_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_ce0),
    .buf_V_1_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_we0),
    .buf_V_1_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_d0),
    .buf_V_1_q0(buf_V_1_q0),
    .buf_V_2_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_address0),
    .buf_V_2_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_ce0),
    .buf_V_2_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_we0),
    .buf_V_2_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_d0),
    .buf_V_2_q0(buf_V_2_q0),
    .buf_V_3_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_address0),
    .buf_V_3_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_ce0),
    .buf_V_3_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_we0),
    .buf_V_3_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_d0),
    .buf_V_3_q0(buf_V_3_q0),
    .buf_V_4_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_address0),
    .buf_V_4_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_ce0),
    .buf_V_4_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_we0),
    .buf_V_4_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_d0),
    .buf_V_4_q0(buf_V_4_q0),
    .buf_V_5_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_address0),
    .buf_V_5_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_ce0),
    .buf_V_5_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_we0),
    .buf_V_5_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_d0),
    .buf_V_5_q0(buf_V_5_q0),
    .buf_V_6_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_address0),
    .buf_V_6_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_ce0),
    .buf_V_6_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_we0),
    .buf_V_6_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_d0),
    .buf_V_6_q0(buf_V_6_q0),
    .buf_V_7_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_address0),
    .buf_V_7_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_ce0),
    .buf_V_7_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_we0),
    .buf_V_7_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_d0),
    .buf_V_7_q0(buf_V_7_q0),
    .buf_V_8_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_address0),
    .buf_V_8_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_ce0),
    .buf_V_8_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_we0),
    .buf_V_8_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_d0),
    .buf_V_8_q0(buf_V_8_q0),
    .buf_V_9_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_address0),
    .buf_V_9_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_ce0),
    .buf_V_9_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_we0),
    .buf_V_9_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_d0),
    .buf_V_9_q0(buf_V_9_q0),
    .buf_V_10_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_address0),
    .buf_V_10_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_ce0),
    .buf_V_10_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_we0),
    .buf_V_10_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_d0),
    .buf_V_10_q0(buf_V_10_q0),
    .buf_V_11_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_address0),
    .buf_V_11_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_ce0),
    .buf_V_11_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_we0),
    .buf_V_11_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_d0),
    .buf_V_11_q0(buf_V_11_q0),
    .buf_V_12_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_address0),
    .buf_V_12_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_ce0),
    .buf_V_12_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_we0),
    .buf_V_12_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_d0),
    .buf_V_12_q0(buf_V_12_q0),
    .buf_V_13_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_address0),
    .buf_V_13_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_ce0),
    .buf_V_13_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_we0),
    .buf_V_13_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_d0),
    .buf_V_13_q0(buf_V_13_q0),
    .buf_V_14_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_address0),
    .buf_V_14_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_ce0),
    .buf_V_14_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_we0),
    .buf_V_14_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_d0),
    .buf_V_14_q0(buf_V_14_q0),
    .buf_V_15_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_address0),
    .buf_V_15_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_ce0),
    .buf_V_15_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_we0),
    .buf_V_15_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_d0),
    .buf_V_15_q0(buf_V_15_q0),
    .out_V_TDATA(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TDATA),
    .out_V_TVALID(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TVALID)
);

StreamingMaxPool_hls_2_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6 grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start),
    .ap_done(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_done),
    .ap_idle(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_idle),
    .ap_ready(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_ready),
    .in0_V_TVALID(in0_V_TVALID),
    .buf_V_15_load_1(buf_V_15_load_reg_699),
    .buf_V_14_load_1(buf_V_14_load_reg_694),
    .buf_V_13_load_1(buf_V_13_load_reg_689),
    .buf_V_12_load_1(buf_V_12_load_reg_684),
    .buf_V_11_load_1(buf_V_11_load_reg_679),
    .buf_V_10_load_1(buf_V_10_load_reg_674),
    .buf_V_9_load_1(buf_V_9_load_reg_669),
    .buf_V_8_load_1(buf_V_8_load_reg_664),
    .buf_V_7_load_1(buf_V_7_load_reg_659),
    .buf_V_6_load_1(buf_V_6_load_reg_654),
    .buf_V_5_load_1(buf_V_5_load_reg_649),
    .buf_V_4_load_1(buf_V_4_load_reg_644),
    .buf_V_3_load_1(buf_V_3_load_reg_639),
    .buf_V_2_load_1(buf_V_2_load_reg_634),
    .buf_V_1_load_1(buf_V_1_load_reg_629),
    .buf_V_load_1(buf_V_load_reg_624),
    .buf_V_15_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_address0),
    .buf_V_15_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_ce0),
    .buf_V_15_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_we0),
    .buf_V_15_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_d0),
    .zext_ln156(select_ln155_reg_534),
    .buf_V_14_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_address0),
    .buf_V_14_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_ce0),
    .buf_V_14_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_we0),
    .buf_V_14_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_d0),
    .buf_V_13_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_address0),
    .buf_V_13_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_ce0),
    .buf_V_13_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_we0),
    .buf_V_13_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_d0),
    .buf_V_12_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_address0),
    .buf_V_12_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_ce0),
    .buf_V_12_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_we0),
    .buf_V_12_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_d0),
    .buf_V_11_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_address0),
    .buf_V_11_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_ce0),
    .buf_V_11_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_we0),
    .buf_V_11_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_d0),
    .buf_V_10_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_address0),
    .buf_V_10_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_ce0),
    .buf_V_10_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_we0),
    .buf_V_10_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_d0),
    .buf_V_9_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_address0),
    .buf_V_9_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_ce0),
    .buf_V_9_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_we0),
    .buf_V_9_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_d0),
    .buf_V_8_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_address0),
    .buf_V_8_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_ce0),
    .buf_V_8_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_we0),
    .buf_V_8_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_d0),
    .buf_V_7_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_address0),
    .buf_V_7_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_ce0),
    .buf_V_7_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_we0),
    .buf_V_7_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_d0),
    .buf_V_6_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_address0),
    .buf_V_6_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_ce0),
    .buf_V_6_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_we0),
    .buf_V_6_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_d0),
    .buf_V_5_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_address0),
    .buf_V_5_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_ce0),
    .buf_V_5_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_we0),
    .buf_V_5_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_d0),
    .buf_V_4_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_address0),
    .buf_V_4_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_ce0),
    .buf_V_4_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_we0),
    .buf_V_4_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_d0),
    .buf_V_3_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_address0),
    .buf_V_3_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_ce0),
    .buf_V_3_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_we0),
    .buf_V_3_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_d0),
    .buf_V_2_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_address0),
    .buf_V_2_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_ce0),
    .buf_V_2_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_we0),
    .buf_V_2_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_d0),
    .buf_V_1_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_address0),
    .buf_V_1_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_ce0),
    .buf_V_1_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_we0),
    .buf_V_1_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_d0),
    .buf_V_address0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_address0),
    .buf_V_ce0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_ce0),
    .buf_V_we0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_we0),
    .buf_V_d0(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_d0),
    .in0_V_TDATA(in0_V_TDATA),
    .in0_V_TREADY(grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_in0_V_TREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start_reg <= 1'b1;
        end else if ((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_ready == 1'b1)) begin
            grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start_reg <= 1'b1;
        end else if ((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_ready == 1'b1)) begin
            grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln155_fu_455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start_reg <= 1'b1;
        end else if ((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_ready == 1'b1)) begin
            grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        indvar_flatten_reg_316 <= add_ln155_reg_529;
    end else if (((icmp_ln154_fu_443_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten_reg_316 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        xp_reg_327 <= add_ln156_reg_619;
    end else if (((icmp_ln154_fu_443_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        xp_reg_327 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        yp_fu_56 <= 6'd0;
    end else if (((icmp_ln155_fu_455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        yp_fu_56 <= yp_2_reg_521;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln155_reg_529 <= add_ln155_fu_461_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln156_reg_619 <= add_ln156_fu_501_p2;
        select_ln155_reg_534 <= select_ln155_fu_473_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_10_load_reg_674 <= buf_V_10_q0;
        buf_V_11_load_reg_679 <= buf_V_11_q0;
        buf_V_12_load_reg_684 <= buf_V_12_q0;
        buf_V_13_load_reg_689 <= buf_V_13_q0;
        buf_V_14_load_reg_694 <= buf_V_14_q0;
        buf_V_15_load_reg_699 <= buf_V_15_q0;
        buf_V_1_load_reg_629 <= buf_V_1_q0;
        buf_V_2_load_reg_634 <= buf_V_2_q0;
        buf_V_3_load_reg_639 <= buf_V_3_q0;
        buf_V_4_load_reg_644 <= buf_V_4_q0;
        buf_V_5_load_reg_649 <= buf_V_5_q0;
        buf_V_6_load_reg_654 <= buf_V_6_q0;
        buf_V_7_load_reg_659 <= buf_V_7_q0;
        buf_V_8_load_reg_664 <= buf_V_8_q0;
        buf_V_9_load_reg_669 <= buf_V_9_q0;
        buf_V_load_reg_624 <= buf_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        yp_2_reg_521 <= yp_2_fu_449_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln154_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln154_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_10_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_10_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_10_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_10_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_address0;
    end else begin
        buf_V_10_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_10_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_10_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_10_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_10_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_ce0;
    end else begin
        buf_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_10_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_10_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_10_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_d0;
    end else begin
        buf_V_10_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_10_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_10_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_10_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_10_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_10_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_10_we0;
    end else begin
        buf_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_11_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_11_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_11_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_11_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_address0;
    end else begin
        buf_V_11_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_11_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_11_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_11_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_11_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_ce0;
    end else begin
        buf_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_11_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_11_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_11_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_d0;
    end else begin
        buf_V_11_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_11_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_11_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_11_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_11_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_11_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_11_we0;
    end else begin
        buf_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_12_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_12_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_12_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_12_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_address0;
    end else begin
        buf_V_12_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_12_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_12_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_12_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_12_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_ce0;
    end else begin
        buf_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_12_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_12_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_12_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_d0;
    end else begin
        buf_V_12_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_12_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_12_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_12_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_12_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_12_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_12_we0;
    end else begin
        buf_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_13_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_13_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_13_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_13_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_address0;
    end else begin
        buf_V_13_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_13_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_13_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_13_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_13_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_ce0;
    end else begin
        buf_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_13_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_13_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_13_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_d0;
    end else begin
        buf_V_13_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_13_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_13_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_13_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_13_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_13_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_13_we0;
    end else begin
        buf_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_14_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_14_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_14_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_14_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_address0;
    end else begin
        buf_V_14_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_14_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_14_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_14_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_14_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_ce0;
    end else begin
        buf_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_14_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_14_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_14_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_d0;
    end else begin
        buf_V_14_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_14_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_14_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_14_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_14_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_14_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_14_we0;
    end else begin
        buf_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_15_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_15_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_15_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_15_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_address0;
    end else begin
        buf_V_15_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_15_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_15_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_15_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_15_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_ce0;
    end else begin
        buf_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_15_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_15_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_15_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_d0;
    end else begin
        buf_V_15_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_15_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_15_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_15_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_15_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_15_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_15_we0;
    end else begin
        buf_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_1_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_1_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_1_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_address0;
    end else begin
        buf_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_1_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_1_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_ce0;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_1_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_1_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_d0;
    end else begin
        buf_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_1_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_1_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_1_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_1_we0;
    end else begin
        buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_2_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_2_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_2_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_2_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_address0;
    end else begin
        buf_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_2_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_2_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_2_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_ce0;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_2_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_2_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_2_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_d0;
    end else begin
        buf_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_2_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_2_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_2_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_2_we0;
    end else begin
        buf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_3_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_3_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_3_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_address0;
    end else begin
        buf_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_3_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_3_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_ce0;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_3_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_3_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_d0;
    end else begin
        buf_V_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_3_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_3_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_3_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_3_we0;
    end else begin
        buf_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_4_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_4_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_4_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_address0;
    end else begin
        buf_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_4_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_4_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_ce0;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_4_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_4_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_d0;
    end else begin
        buf_V_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_4_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_4_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_4_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_4_we0;
    end else begin
        buf_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_5_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_5_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_5_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_5_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_address0;
    end else begin
        buf_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_5_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_5_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_5_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_ce0;
    end else begin
        buf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_5_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_5_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_5_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_d0;
    end else begin
        buf_V_5_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_5_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_5_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_5_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_5_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_5_we0;
    end else begin
        buf_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_6_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_6_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_6_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_6_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_address0;
    end else begin
        buf_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_6_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_6_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_6_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_ce0;
    end else begin
        buf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_6_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_6_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_6_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_d0;
    end else begin
        buf_V_6_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_6_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_6_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_6_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_6_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_6_we0;
    end else begin
        buf_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_7_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_7_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_7_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_7_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_address0;
    end else begin
        buf_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_7_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_7_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_7_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_ce0;
    end else begin
        buf_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_7_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_7_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_7_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_d0;
    end else begin
        buf_V_7_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_7_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_7_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_7_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_7_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_7_we0;
    end else begin
        buf_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_8_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_8_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_8_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_8_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_address0;
    end else begin
        buf_V_8_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_8_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_8_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_8_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_8_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_ce0;
    end else begin
        buf_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_8_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_8_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_8_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_d0;
    end else begin
        buf_V_8_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_8_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_8_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_8_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_8_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_8_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_8_we0;
    end else begin
        buf_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_9_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_9_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_9_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_9_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_address0;
    end else begin
        buf_V_9_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_9_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_9_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_9_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_9_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_ce0;
    end else begin
        buf_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_9_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_9_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_9_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_d0;
    end else begin
        buf_V_9_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_9_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_9_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_9_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_9_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_9_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_9_we0;
    end else begin
        buf_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_address0 = zext_ln156_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_address0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_address0;
    end else begin
        buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln155_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        buf_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_ce0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_ce0;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_d0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_d0;
    end else begin
        buf_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_buf_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_buf_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_we0 = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_buf_V_we0;
    end else begin
        buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        in0_V_TREADY = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_in0_V_TREADY;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln154_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln155_fu_455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln155_fu_461_p2 = (indvar_flatten_reg_316 + 7'd1);

assign add_ln156_fu_501_p2 = (select_ln155_fu_473_p3 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_147_1_fu_338_ap_start_reg;

assign grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_158_6_fu_396_ap_start_reg;

assign grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_ap_start_reg;

assign grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TREADY = (out_V_TREADY & ap_CS_fsm_state8);

assign icmp_ln154_fu_443_p2 = ((yp_fu_56 == 6'd52) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_455_p2 = ((indvar_flatten_reg_316 == 7'd104) ? 1'b1 : 1'b0);

assign icmp_ln156_fu_467_p2 = ((xp_reg_327 == 6'd52) ? 1'b1 : 1'b0);

assign out_V_TDATA = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TDATA;

assign out_V_TVALID = grp_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8_fu_374_out_V_TVALID;

assign select_ln155_fu_473_p3 = ((icmp_ln156_fu_467_p2[0:0] == 1'b1) ? 6'd0 : xp_reg_327);

assign yp_2_fu_449_p2 = (yp_fu_56 + 6'd1);

assign zext_ln156_fu_481_p1 = select_ln155_fu_473_p3;

endmodule //StreamingMaxPool_hls_2_StreamingMaxPool_Precision_104u_2u_16u_ap_uint_3_0_48_s
