// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_hls_4_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_V_TREADY,
        buf_V_address0,
        buf_V_ce0,
        buf_V_we0,
        buf_V_d0,
        buf_V_q0,
        buf_V_1_address0,
        buf_V_1_ce0,
        buf_V_1_we0,
        buf_V_1_d0,
        buf_V_1_q0,
        buf_V_2_address0,
        buf_V_2_ce0,
        buf_V_2_we0,
        buf_V_2_d0,
        buf_V_2_q0,
        buf_V_3_address0,
        buf_V_3_ce0,
        buf_V_3_we0,
        buf_V_3_d0,
        buf_V_3_q0,
        buf_V_4_address0,
        buf_V_4_ce0,
        buf_V_4_we0,
        buf_V_4_d0,
        buf_V_4_q0,
        buf_V_5_address0,
        buf_V_5_ce0,
        buf_V_5_we0,
        buf_V_5_d0,
        buf_V_5_q0,
        buf_V_6_address0,
        buf_V_6_ce0,
        buf_V_6_we0,
        buf_V_6_d0,
        buf_V_6_q0,
        buf_V_7_address0,
        buf_V_7_ce0,
        buf_V_7_we0,
        buf_V_7_d0,
        buf_V_7_q0,
        buf_V_8_address0,
        buf_V_8_ce0,
        buf_V_8_we0,
        buf_V_8_d0,
        buf_V_8_q0,
        buf_V_9_address0,
        buf_V_9_ce0,
        buf_V_9_we0,
        buf_V_9_d0,
        buf_V_9_q0,
        buf_V_10_address0,
        buf_V_10_ce0,
        buf_V_10_we0,
        buf_V_10_d0,
        buf_V_10_q0,
        buf_V_11_address0,
        buf_V_11_ce0,
        buf_V_11_we0,
        buf_V_11_d0,
        buf_V_11_q0,
        buf_V_12_address0,
        buf_V_12_ce0,
        buf_V_12_we0,
        buf_V_12_d0,
        buf_V_12_q0,
        buf_V_13_address0,
        buf_V_13_ce0,
        buf_V_13_we0,
        buf_V_13_d0,
        buf_V_13_q0,
        buf_V_14_address0,
        buf_V_14_ce0,
        buf_V_14_we0,
        buf_V_14_d0,
        buf_V_14_q0,
        buf_V_15_address0,
        buf_V_15_ce0,
        buf_V_15_we0,
        buf_V_15_d0,
        buf_V_15_q0,
        buf_V_16_address0,
        buf_V_16_ce0,
        buf_V_16_we0,
        buf_V_16_d0,
        buf_V_16_q0,
        buf_V_17_address0,
        buf_V_17_ce0,
        buf_V_17_we0,
        buf_V_17_d0,
        buf_V_17_q0,
        buf_V_18_address0,
        buf_V_18_ce0,
        buf_V_18_we0,
        buf_V_18_d0,
        buf_V_18_q0,
        buf_V_19_address0,
        buf_V_19_ce0,
        buf_V_19_we0,
        buf_V_19_d0,
        buf_V_19_q0,
        buf_V_20_address0,
        buf_V_20_ce0,
        buf_V_20_we0,
        buf_V_20_d0,
        buf_V_20_q0,
        buf_V_21_address0,
        buf_V_21_ce0,
        buf_V_21_we0,
        buf_V_21_d0,
        buf_V_21_q0,
        buf_V_22_address0,
        buf_V_22_ce0,
        buf_V_22_we0,
        buf_V_22_d0,
        buf_V_22_q0,
        buf_V_23_address0,
        buf_V_23_ce0,
        buf_V_23_we0,
        buf_V_23_d0,
        buf_V_23_q0,
        buf_V_24_address0,
        buf_V_24_ce0,
        buf_V_24_we0,
        buf_V_24_d0,
        buf_V_24_q0,
        buf_V_25_address0,
        buf_V_25_ce0,
        buf_V_25_we0,
        buf_V_25_d0,
        buf_V_25_q0,
        buf_V_26_address0,
        buf_V_26_ce0,
        buf_V_26_we0,
        buf_V_26_d0,
        buf_V_26_q0,
        buf_V_27_address0,
        buf_V_27_ce0,
        buf_V_27_we0,
        buf_V_27_d0,
        buf_V_27_q0,
        buf_V_28_address0,
        buf_V_28_ce0,
        buf_V_28_we0,
        buf_V_28_d0,
        buf_V_28_q0,
        buf_V_29_address0,
        buf_V_29_ce0,
        buf_V_29_we0,
        buf_V_29_d0,
        buf_V_29_q0,
        buf_V_30_address0,
        buf_V_30_ce0,
        buf_V_30_we0,
        buf_V_30_d0,
        buf_V_30_q0,
        buf_V_31_address0,
        buf_V_31_ce0,
        buf_V_31_we0,
        buf_V_31_d0,
        buf_V_31_q0,
        buf_V_32_address0,
        buf_V_32_ce0,
        buf_V_32_we0,
        buf_V_32_d0,
        buf_V_32_q0,
        buf_V_33_address0,
        buf_V_33_ce0,
        buf_V_33_we0,
        buf_V_33_d0,
        buf_V_33_q0,
        buf_V_34_address0,
        buf_V_34_ce0,
        buf_V_34_we0,
        buf_V_34_d0,
        buf_V_34_q0,
        buf_V_35_address0,
        buf_V_35_ce0,
        buf_V_35_we0,
        buf_V_35_d0,
        buf_V_35_q0,
        buf_V_36_address0,
        buf_V_36_ce0,
        buf_V_36_we0,
        buf_V_36_d0,
        buf_V_36_q0,
        buf_V_37_address0,
        buf_V_37_ce0,
        buf_V_37_we0,
        buf_V_37_d0,
        buf_V_37_q0,
        buf_V_38_address0,
        buf_V_38_ce0,
        buf_V_38_we0,
        buf_V_38_d0,
        buf_V_38_q0,
        buf_V_39_address0,
        buf_V_39_ce0,
        buf_V_39_we0,
        buf_V_39_d0,
        buf_V_39_q0,
        buf_V_40_address0,
        buf_V_40_ce0,
        buf_V_40_we0,
        buf_V_40_d0,
        buf_V_40_q0,
        buf_V_41_address0,
        buf_V_41_ce0,
        buf_V_41_we0,
        buf_V_41_d0,
        buf_V_41_q0,
        buf_V_42_address0,
        buf_V_42_ce0,
        buf_V_42_we0,
        buf_V_42_d0,
        buf_V_42_q0,
        buf_V_43_address0,
        buf_V_43_ce0,
        buf_V_43_we0,
        buf_V_43_d0,
        buf_V_43_q0,
        buf_V_44_address0,
        buf_V_44_ce0,
        buf_V_44_we0,
        buf_V_44_d0,
        buf_V_44_q0,
        buf_V_45_address0,
        buf_V_45_ce0,
        buf_V_45_we0,
        buf_V_45_d0,
        buf_V_45_q0,
        buf_V_46_address0,
        buf_V_46_ce0,
        buf_V_46_we0,
        buf_V_46_d0,
        buf_V_46_q0,
        buf_V_47_address0,
        buf_V_47_ce0,
        buf_V_47_we0,
        buf_V_47_d0,
        buf_V_47_q0,
        buf_V_48_address0,
        buf_V_48_ce0,
        buf_V_48_we0,
        buf_V_48_d0,
        buf_V_48_q0,
        buf_V_49_address0,
        buf_V_49_ce0,
        buf_V_49_we0,
        buf_V_49_d0,
        buf_V_49_q0,
        buf_V_50_address0,
        buf_V_50_ce0,
        buf_V_50_we0,
        buf_V_50_d0,
        buf_V_50_q0,
        buf_V_51_address0,
        buf_V_51_ce0,
        buf_V_51_we0,
        buf_V_51_d0,
        buf_V_51_q0,
        buf_V_52_address0,
        buf_V_52_ce0,
        buf_V_52_we0,
        buf_V_52_d0,
        buf_V_52_q0,
        buf_V_53_address0,
        buf_V_53_ce0,
        buf_V_53_we0,
        buf_V_53_d0,
        buf_V_53_q0,
        buf_V_54_address0,
        buf_V_54_ce0,
        buf_V_54_we0,
        buf_V_54_d0,
        buf_V_54_q0,
        buf_V_55_address0,
        buf_V_55_ce0,
        buf_V_55_we0,
        buf_V_55_d0,
        buf_V_55_q0,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_V_TREADY;
output  [3:0] buf_V_address0;
output   buf_V_ce0;
output   buf_V_we0;
output  [2:0] buf_V_d0;
input  [2:0] buf_V_q0;
output  [3:0] buf_V_1_address0;
output   buf_V_1_ce0;
output   buf_V_1_we0;
output  [2:0] buf_V_1_d0;
input  [2:0] buf_V_1_q0;
output  [3:0] buf_V_2_address0;
output   buf_V_2_ce0;
output   buf_V_2_we0;
output  [2:0] buf_V_2_d0;
input  [2:0] buf_V_2_q0;
output  [3:0] buf_V_3_address0;
output   buf_V_3_ce0;
output   buf_V_3_we0;
output  [2:0] buf_V_3_d0;
input  [2:0] buf_V_3_q0;
output  [3:0] buf_V_4_address0;
output   buf_V_4_ce0;
output   buf_V_4_we0;
output  [2:0] buf_V_4_d0;
input  [2:0] buf_V_4_q0;
output  [3:0] buf_V_5_address0;
output   buf_V_5_ce0;
output   buf_V_5_we0;
output  [2:0] buf_V_5_d0;
input  [2:0] buf_V_5_q0;
output  [3:0] buf_V_6_address0;
output   buf_V_6_ce0;
output   buf_V_6_we0;
output  [2:0] buf_V_6_d0;
input  [2:0] buf_V_6_q0;
output  [3:0] buf_V_7_address0;
output   buf_V_7_ce0;
output   buf_V_7_we0;
output  [2:0] buf_V_7_d0;
input  [2:0] buf_V_7_q0;
output  [3:0] buf_V_8_address0;
output   buf_V_8_ce0;
output   buf_V_8_we0;
output  [2:0] buf_V_8_d0;
input  [2:0] buf_V_8_q0;
output  [3:0] buf_V_9_address0;
output   buf_V_9_ce0;
output   buf_V_9_we0;
output  [2:0] buf_V_9_d0;
input  [2:0] buf_V_9_q0;
output  [3:0] buf_V_10_address0;
output   buf_V_10_ce0;
output   buf_V_10_we0;
output  [2:0] buf_V_10_d0;
input  [2:0] buf_V_10_q0;
output  [3:0] buf_V_11_address0;
output   buf_V_11_ce0;
output   buf_V_11_we0;
output  [2:0] buf_V_11_d0;
input  [2:0] buf_V_11_q0;
output  [3:0] buf_V_12_address0;
output   buf_V_12_ce0;
output   buf_V_12_we0;
output  [2:0] buf_V_12_d0;
input  [2:0] buf_V_12_q0;
output  [3:0] buf_V_13_address0;
output   buf_V_13_ce0;
output   buf_V_13_we0;
output  [2:0] buf_V_13_d0;
input  [2:0] buf_V_13_q0;
output  [3:0] buf_V_14_address0;
output   buf_V_14_ce0;
output   buf_V_14_we0;
output  [2:0] buf_V_14_d0;
input  [2:0] buf_V_14_q0;
output  [3:0] buf_V_15_address0;
output   buf_V_15_ce0;
output   buf_V_15_we0;
output  [2:0] buf_V_15_d0;
input  [2:0] buf_V_15_q0;
output  [3:0] buf_V_16_address0;
output   buf_V_16_ce0;
output   buf_V_16_we0;
output  [2:0] buf_V_16_d0;
input  [2:0] buf_V_16_q0;
output  [3:0] buf_V_17_address0;
output   buf_V_17_ce0;
output   buf_V_17_we0;
output  [2:0] buf_V_17_d0;
input  [2:0] buf_V_17_q0;
output  [3:0] buf_V_18_address0;
output   buf_V_18_ce0;
output   buf_V_18_we0;
output  [2:0] buf_V_18_d0;
input  [2:0] buf_V_18_q0;
output  [3:0] buf_V_19_address0;
output   buf_V_19_ce0;
output   buf_V_19_we0;
output  [2:0] buf_V_19_d0;
input  [2:0] buf_V_19_q0;
output  [3:0] buf_V_20_address0;
output   buf_V_20_ce0;
output   buf_V_20_we0;
output  [2:0] buf_V_20_d0;
input  [2:0] buf_V_20_q0;
output  [3:0] buf_V_21_address0;
output   buf_V_21_ce0;
output   buf_V_21_we0;
output  [2:0] buf_V_21_d0;
input  [2:0] buf_V_21_q0;
output  [3:0] buf_V_22_address0;
output   buf_V_22_ce0;
output   buf_V_22_we0;
output  [2:0] buf_V_22_d0;
input  [2:0] buf_V_22_q0;
output  [3:0] buf_V_23_address0;
output   buf_V_23_ce0;
output   buf_V_23_we0;
output  [2:0] buf_V_23_d0;
input  [2:0] buf_V_23_q0;
output  [3:0] buf_V_24_address0;
output   buf_V_24_ce0;
output   buf_V_24_we0;
output  [2:0] buf_V_24_d0;
input  [2:0] buf_V_24_q0;
output  [3:0] buf_V_25_address0;
output   buf_V_25_ce0;
output   buf_V_25_we0;
output  [2:0] buf_V_25_d0;
input  [2:0] buf_V_25_q0;
output  [3:0] buf_V_26_address0;
output   buf_V_26_ce0;
output   buf_V_26_we0;
output  [2:0] buf_V_26_d0;
input  [2:0] buf_V_26_q0;
output  [3:0] buf_V_27_address0;
output   buf_V_27_ce0;
output   buf_V_27_we0;
output  [2:0] buf_V_27_d0;
input  [2:0] buf_V_27_q0;
output  [3:0] buf_V_28_address0;
output   buf_V_28_ce0;
output   buf_V_28_we0;
output  [2:0] buf_V_28_d0;
input  [2:0] buf_V_28_q0;
output  [3:0] buf_V_29_address0;
output   buf_V_29_ce0;
output   buf_V_29_we0;
output  [2:0] buf_V_29_d0;
input  [2:0] buf_V_29_q0;
output  [3:0] buf_V_30_address0;
output   buf_V_30_ce0;
output   buf_V_30_we0;
output  [2:0] buf_V_30_d0;
input  [2:0] buf_V_30_q0;
output  [3:0] buf_V_31_address0;
output   buf_V_31_ce0;
output   buf_V_31_we0;
output  [2:0] buf_V_31_d0;
input  [2:0] buf_V_31_q0;
output  [3:0] buf_V_32_address0;
output   buf_V_32_ce0;
output   buf_V_32_we0;
output  [2:0] buf_V_32_d0;
input  [2:0] buf_V_32_q0;
output  [3:0] buf_V_33_address0;
output   buf_V_33_ce0;
output   buf_V_33_we0;
output  [2:0] buf_V_33_d0;
input  [2:0] buf_V_33_q0;
output  [3:0] buf_V_34_address0;
output   buf_V_34_ce0;
output   buf_V_34_we0;
output  [2:0] buf_V_34_d0;
input  [2:0] buf_V_34_q0;
output  [3:0] buf_V_35_address0;
output   buf_V_35_ce0;
output   buf_V_35_we0;
output  [2:0] buf_V_35_d0;
input  [2:0] buf_V_35_q0;
output  [3:0] buf_V_36_address0;
output   buf_V_36_ce0;
output   buf_V_36_we0;
output  [2:0] buf_V_36_d0;
input  [2:0] buf_V_36_q0;
output  [3:0] buf_V_37_address0;
output   buf_V_37_ce0;
output   buf_V_37_we0;
output  [2:0] buf_V_37_d0;
input  [2:0] buf_V_37_q0;
output  [3:0] buf_V_38_address0;
output   buf_V_38_ce0;
output   buf_V_38_we0;
output  [2:0] buf_V_38_d0;
input  [2:0] buf_V_38_q0;
output  [3:0] buf_V_39_address0;
output   buf_V_39_ce0;
output   buf_V_39_we0;
output  [2:0] buf_V_39_d0;
input  [2:0] buf_V_39_q0;
output  [3:0] buf_V_40_address0;
output   buf_V_40_ce0;
output   buf_V_40_we0;
output  [2:0] buf_V_40_d0;
input  [2:0] buf_V_40_q0;
output  [3:0] buf_V_41_address0;
output   buf_V_41_ce0;
output   buf_V_41_we0;
output  [2:0] buf_V_41_d0;
input  [2:0] buf_V_41_q0;
output  [3:0] buf_V_42_address0;
output   buf_V_42_ce0;
output   buf_V_42_we0;
output  [2:0] buf_V_42_d0;
input  [2:0] buf_V_42_q0;
output  [3:0] buf_V_43_address0;
output   buf_V_43_ce0;
output   buf_V_43_we0;
output  [2:0] buf_V_43_d0;
input  [2:0] buf_V_43_q0;
output  [3:0] buf_V_44_address0;
output   buf_V_44_ce0;
output   buf_V_44_we0;
output  [2:0] buf_V_44_d0;
input  [2:0] buf_V_44_q0;
output  [3:0] buf_V_45_address0;
output   buf_V_45_ce0;
output   buf_V_45_we0;
output  [2:0] buf_V_45_d0;
input  [2:0] buf_V_45_q0;
output  [3:0] buf_V_46_address0;
output   buf_V_46_ce0;
output   buf_V_46_we0;
output  [2:0] buf_V_46_d0;
input  [2:0] buf_V_46_q0;
output  [3:0] buf_V_47_address0;
output   buf_V_47_ce0;
output   buf_V_47_we0;
output  [2:0] buf_V_47_d0;
input  [2:0] buf_V_47_q0;
output  [3:0] buf_V_48_address0;
output   buf_V_48_ce0;
output   buf_V_48_we0;
output  [2:0] buf_V_48_d0;
input  [2:0] buf_V_48_q0;
output  [3:0] buf_V_49_address0;
output   buf_V_49_ce0;
output   buf_V_49_we0;
output  [2:0] buf_V_49_d0;
input  [2:0] buf_V_49_q0;
output  [3:0] buf_V_50_address0;
output   buf_V_50_ce0;
output   buf_V_50_we0;
output  [2:0] buf_V_50_d0;
input  [2:0] buf_V_50_q0;
output  [3:0] buf_V_51_address0;
output   buf_V_51_ce0;
output   buf_V_51_we0;
output  [2:0] buf_V_51_d0;
input  [2:0] buf_V_51_q0;
output  [3:0] buf_V_52_address0;
output   buf_V_52_ce0;
output   buf_V_52_we0;
output  [2:0] buf_V_52_d0;
input  [2:0] buf_V_52_q0;
output  [3:0] buf_V_53_address0;
output   buf_V_53_ce0;
output   buf_V_53_we0;
output  [2:0] buf_V_53_d0;
input  [2:0] buf_V_53_q0;
output  [3:0] buf_V_54_address0;
output   buf_V_54_ce0;
output   buf_V_54_we0;
output  [2:0] buf_V_54_d0;
input  [2:0] buf_V_54_q0;
output  [3:0] buf_V_55_address0;
output   buf_V_55_ce0;
output   buf_V_55_we0;
output  [2:0] buf_V_55_d0;
input  [2:0] buf_V_55_q0;
output  [167:0] out_V_TDATA;
output   out_V_TVALID;

reg ap_idle;
reg buf_V_ce0;
reg buf_V_we0;
reg buf_V_1_ce0;
reg buf_V_1_we0;
reg buf_V_2_ce0;
reg buf_V_2_we0;
reg buf_V_3_ce0;
reg buf_V_3_we0;
reg buf_V_4_ce0;
reg buf_V_4_we0;
reg buf_V_5_ce0;
reg buf_V_5_we0;
reg buf_V_6_ce0;
reg buf_V_6_we0;
reg buf_V_7_ce0;
reg buf_V_7_we0;
reg buf_V_8_ce0;
reg buf_V_8_we0;
reg buf_V_9_ce0;
reg buf_V_9_we0;
reg buf_V_10_ce0;
reg buf_V_10_we0;
reg buf_V_11_ce0;
reg buf_V_11_we0;
reg buf_V_12_ce0;
reg buf_V_12_we0;
reg buf_V_13_ce0;
reg buf_V_13_we0;
reg buf_V_14_ce0;
reg buf_V_14_we0;
reg buf_V_15_ce0;
reg buf_V_15_we0;
reg buf_V_16_ce0;
reg buf_V_16_we0;
reg buf_V_17_ce0;
reg buf_V_17_we0;
reg buf_V_18_ce0;
reg buf_V_18_we0;
reg buf_V_19_ce0;
reg buf_V_19_we0;
reg buf_V_20_ce0;
reg buf_V_20_we0;
reg buf_V_21_ce0;
reg buf_V_21_we0;
reg buf_V_22_ce0;
reg buf_V_22_we0;
reg buf_V_23_ce0;
reg buf_V_23_we0;
reg buf_V_24_ce0;
reg buf_V_24_we0;
reg buf_V_25_ce0;
reg buf_V_25_we0;
reg buf_V_26_ce0;
reg buf_V_26_we0;
reg buf_V_27_ce0;
reg buf_V_27_we0;
reg buf_V_28_ce0;
reg buf_V_28_we0;
reg buf_V_29_ce0;
reg buf_V_29_we0;
reg buf_V_30_ce0;
reg buf_V_30_we0;
reg buf_V_31_ce0;
reg buf_V_31_we0;
reg buf_V_32_ce0;
reg buf_V_32_we0;
reg buf_V_33_ce0;
reg buf_V_33_we0;
reg buf_V_34_ce0;
reg buf_V_34_we0;
reg buf_V_35_ce0;
reg buf_V_35_we0;
reg buf_V_36_ce0;
reg buf_V_36_we0;
reg buf_V_37_ce0;
reg buf_V_37_we0;
reg buf_V_38_ce0;
reg buf_V_38_we0;
reg buf_V_39_ce0;
reg buf_V_39_we0;
reg buf_V_40_ce0;
reg buf_V_40_we0;
reg buf_V_41_ce0;
reg buf_V_41_we0;
reg buf_V_42_ce0;
reg buf_V_42_we0;
reg buf_V_43_ce0;
reg buf_V_43_we0;
reg buf_V_44_ce0;
reg buf_V_44_we0;
reg buf_V_45_ce0;
reg buf_V_45_we0;
reg buf_V_46_ce0;
reg buf_V_46_we0;
reg buf_V_47_ce0;
reg buf_V_47_we0;
reg buf_V_48_ce0;
reg buf_V_48_we0;
reg buf_V_49_ce0;
reg buf_V_49_we0;
reg buf_V_50_ce0;
reg buf_V_50_we0;
reg buf_V_51_ce0;
reg buf_V_51_we0;
reg buf_V_52_ce0;
reg buf_V_52_we0;
reg buf_V_53_ce0;
reg buf_V_53_we0;
reg buf_V_54_ce0;
reg buf_V_54_we0;
reg buf_V_55_ce0;
reg buf_V_55_we0;
reg out_V_TVALID;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln174_reg_1158;
wire   [0:0] icmp_ln174_reg_1158_pp0_iter0_reg;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
wire   [0:0] icmp_ln174_fu_957_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_V_TDATA_blk_n;
wire   [63:0] outpix_cast_fu_969_p1;
reg   [3:0] outpix_fu_154;
wire   [3:0] add_ln174_fu_963_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_outpix_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    ap_start_int;
reg    ap_condition_919;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

StreamingMaxPool_hls_4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_919)) begin
        if ((icmp_ln174_fu_957_p2 == 1'd0)) begin
            outpix_fu_154 <= add_ln174_fu_963_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            outpix_fu_154 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln174_reg_1158 <= icmp_ln174_fu_957_p2;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_outpix_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_outpix_1 = outpix_fu_154;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_10_ce0 = 1'b1;
    end else begin
        buf_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_10_we0 = 1'b1;
    end else begin
        buf_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_11_ce0 = 1'b1;
    end else begin
        buf_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_11_we0 = 1'b1;
    end else begin
        buf_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_12_ce0 = 1'b1;
    end else begin
        buf_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_12_we0 = 1'b1;
    end else begin
        buf_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_13_ce0 = 1'b1;
    end else begin
        buf_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_13_we0 = 1'b1;
    end else begin
        buf_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_14_ce0 = 1'b1;
    end else begin
        buf_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_14_we0 = 1'b1;
    end else begin
        buf_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_15_ce0 = 1'b1;
    end else begin
        buf_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_15_we0 = 1'b1;
    end else begin
        buf_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_16_ce0 = 1'b1;
    end else begin
        buf_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_16_we0 = 1'b1;
    end else begin
        buf_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_17_ce0 = 1'b1;
    end else begin
        buf_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_17_we0 = 1'b1;
    end else begin
        buf_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_18_ce0 = 1'b1;
    end else begin
        buf_V_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_18_we0 = 1'b1;
    end else begin
        buf_V_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_19_ce0 = 1'b1;
    end else begin
        buf_V_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_19_we0 = 1'b1;
    end else begin
        buf_V_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_1_we0 = 1'b1;
    end else begin
        buf_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_20_ce0 = 1'b1;
    end else begin
        buf_V_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_20_we0 = 1'b1;
    end else begin
        buf_V_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_21_ce0 = 1'b1;
    end else begin
        buf_V_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_21_we0 = 1'b1;
    end else begin
        buf_V_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_22_ce0 = 1'b1;
    end else begin
        buf_V_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_22_we0 = 1'b1;
    end else begin
        buf_V_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_23_ce0 = 1'b1;
    end else begin
        buf_V_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_23_we0 = 1'b1;
    end else begin
        buf_V_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_24_ce0 = 1'b1;
    end else begin
        buf_V_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_24_we0 = 1'b1;
    end else begin
        buf_V_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_25_ce0 = 1'b1;
    end else begin
        buf_V_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_25_we0 = 1'b1;
    end else begin
        buf_V_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_26_ce0 = 1'b1;
    end else begin
        buf_V_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_26_we0 = 1'b1;
    end else begin
        buf_V_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_27_ce0 = 1'b1;
    end else begin
        buf_V_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_27_we0 = 1'b1;
    end else begin
        buf_V_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_28_ce0 = 1'b1;
    end else begin
        buf_V_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_28_we0 = 1'b1;
    end else begin
        buf_V_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_29_ce0 = 1'b1;
    end else begin
        buf_V_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_29_we0 = 1'b1;
    end else begin
        buf_V_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_2_we0 = 1'b1;
    end else begin
        buf_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_30_ce0 = 1'b1;
    end else begin
        buf_V_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_30_we0 = 1'b1;
    end else begin
        buf_V_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_31_ce0 = 1'b1;
    end else begin
        buf_V_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_31_we0 = 1'b1;
    end else begin
        buf_V_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_32_ce0 = 1'b1;
    end else begin
        buf_V_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_32_we0 = 1'b1;
    end else begin
        buf_V_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_33_ce0 = 1'b1;
    end else begin
        buf_V_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_33_we0 = 1'b1;
    end else begin
        buf_V_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_34_ce0 = 1'b1;
    end else begin
        buf_V_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_34_we0 = 1'b1;
    end else begin
        buf_V_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_35_ce0 = 1'b1;
    end else begin
        buf_V_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_35_we0 = 1'b1;
    end else begin
        buf_V_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_36_ce0 = 1'b1;
    end else begin
        buf_V_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_36_we0 = 1'b1;
    end else begin
        buf_V_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_37_ce0 = 1'b1;
    end else begin
        buf_V_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_37_we0 = 1'b1;
    end else begin
        buf_V_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_38_ce0 = 1'b1;
    end else begin
        buf_V_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_38_we0 = 1'b1;
    end else begin
        buf_V_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_39_ce0 = 1'b1;
    end else begin
        buf_V_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_39_we0 = 1'b1;
    end else begin
        buf_V_39_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_3_ce0 = 1'b1;
    end else begin
        buf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_3_we0 = 1'b1;
    end else begin
        buf_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_40_ce0 = 1'b1;
    end else begin
        buf_V_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_40_we0 = 1'b1;
    end else begin
        buf_V_40_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_41_ce0 = 1'b1;
    end else begin
        buf_V_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_41_we0 = 1'b1;
    end else begin
        buf_V_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_42_ce0 = 1'b1;
    end else begin
        buf_V_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_42_we0 = 1'b1;
    end else begin
        buf_V_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_43_ce0 = 1'b1;
    end else begin
        buf_V_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_43_we0 = 1'b1;
    end else begin
        buf_V_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_44_ce0 = 1'b1;
    end else begin
        buf_V_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_44_we0 = 1'b1;
    end else begin
        buf_V_44_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_45_ce0 = 1'b1;
    end else begin
        buf_V_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_45_we0 = 1'b1;
    end else begin
        buf_V_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_46_ce0 = 1'b1;
    end else begin
        buf_V_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_46_we0 = 1'b1;
    end else begin
        buf_V_46_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_47_ce0 = 1'b1;
    end else begin
        buf_V_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_47_we0 = 1'b1;
    end else begin
        buf_V_47_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_48_ce0 = 1'b1;
    end else begin
        buf_V_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_48_we0 = 1'b1;
    end else begin
        buf_V_48_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_49_ce0 = 1'b1;
    end else begin
        buf_V_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_49_we0 = 1'b1;
    end else begin
        buf_V_49_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_4_ce0 = 1'b1;
    end else begin
        buf_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_4_we0 = 1'b1;
    end else begin
        buf_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_50_ce0 = 1'b1;
    end else begin
        buf_V_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_50_we0 = 1'b1;
    end else begin
        buf_V_50_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_51_ce0 = 1'b1;
    end else begin
        buf_V_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_51_we0 = 1'b1;
    end else begin
        buf_V_51_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_52_ce0 = 1'b1;
    end else begin
        buf_V_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_52_we0 = 1'b1;
    end else begin
        buf_V_52_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_53_ce0 = 1'b1;
    end else begin
        buf_V_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_53_we0 = 1'b1;
    end else begin
        buf_V_53_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_54_ce0 = 1'b1;
    end else begin
        buf_V_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_54_we0 = 1'b1;
    end else begin
        buf_V_54_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_55_ce0 = 1'b1;
    end else begin
        buf_V_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_55_we0 = 1'b1;
    end else begin
        buf_V_55_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_5_ce0 = 1'b1;
    end else begin
        buf_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_5_we0 = 1'b1;
    end else begin
        buf_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_6_ce0 = 1'b1;
    end else begin
        buf_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_6_we0 = 1'b1;
    end else begin
        buf_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_7_ce0 = 1'b1;
    end else begin
        buf_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_7_we0 = 1'b1;
    end else begin
        buf_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_8_ce0 = 1'b1;
    end else begin
        buf_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_8_we0 = 1'b1;
    end else begin
        buf_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_9_ce0 = 1'b1;
    end else begin
        buf_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_9_we0 = 1'b1;
    end else begin
        buf_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (icmp_ln174_fu_957_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buf_V_we0 = 1'b1;
    end else begin
        buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln174_reg_1158 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & (icmp_ln174_reg_1158 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter0_fsm_state1))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else if (((~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))) & (icmp_ln174_reg_1158_pp0_iter0_reg == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln174_fu_963_p2 = (ap_sig_allocacmp_outpix_1 + 4'd1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_919 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln174_reg_1158 == 1'd0) & (out_V_TREADY == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buf_V_10_address0 = outpix_cast_fu_969_p1;

assign buf_V_10_d0 = 3'd0;

assign buf_V_11_address0 = outpix_cast_fu_969_p1;

assign buf_V_11_d0 = 3'd0;

assign buf_V_12_address0 = outpix_cast_fu_969_p1;

assign buf_V_12_d0 = 3'd0;

assign buf_V_13_address0 = outpix_cast_fu_969_p1;

assign buf_V_13_d0 = 3'd0;

assign buf_V_14_address0 = outpix_cast_fu_969_p1;

assign buf_V_14_d0 = 3'd0;

assign buf_V_15_address0 = outpix_cast_fu_969_p1;

assign buf_V_15_d0 = 3'd0;

assign buf_V_16_address0 = outpix_cast_fu_969_p1;

assign buf_V_16_d0 = 3'd0;

assign buf_V_17_address0 = outpix_cast_fu_969_p1;

assign buf_V_17_d0 = 3'd0;

assign buf_V_18_address0 = outpix_cast_fu_969_p1;

assign buf_V_18_d0 = 3'd0;

assign buf_V_19_address0 = outpix_cast_fu_969_p1;

assign buf_V_19_d0 = 3'd0;

assign buf_V_1_address0 = outpix_cast_fu_969_p1;

assign buf_V_1_d0 = 3'd0;

assign buf_V_20_address0 = outpix_cast_fu_969_p1;

assign buf_V_20_d0 = 3'd0;

assign buf_V_21_address0 = outpix_cast_fu_969_p1;

assign buf_V_21_d0 = 3'd0;

assign buf_V_22_address0 = outpix_cast_fu_969_p1;

assign buf_V_22_d0 = 3'd0;

assign buf_V_23_address0 = outpix_cast_fu_969_p1;

assign buf_V_23_d0 = 3'd0;

assign buf_V_24_address0 = outpix_cast_fu_969_p1;

assign buf_V_24_d0 = 3'd0;

assign buf_V_25_address0 = outpix_cast_fu_969_p1;

assign buf_V_25_d0 = 3'd0;

assign buf_V_26_address0 = outpix_cast_fu_969_p1;

assign buf_V_26_d0 = 3'd0;

assign buf_V_27_address0 = outpix_cast_fu_969_p1;

assign buf_V_27_d0 = 3'd0;

assign buf_V_28_address0 = outpix_cast_fu_969_p1;

assign buf_V_28_d0 = 3'd0;

assign buf_V_29_address0 = outpix_cast_fu_969_p1;

assign buf_V_29_d0 = 3'd0;

assign buf_V_2_address0 = outpix_cast_fu_969_p1;

assign buf_V_2_d0 = 3'd0;

assign buf_V_30_address0 = outpix_cast_fu_969_p1;

assign buf_V_30_d0 = 3'd0;

assign buf_V_31_address0 = outpix_cast_fu_969_p1;

assign buf_V_31_d0 = 3'd0;

assign buf_V_32_address0 = outpix_cast_fu_969_p1;

assign buf_V_32_d0 = 3'd0;

assign buf_V_33_address0 = outpix_cast_fu_969_p1;

assign buf_V_33_d0 = 3'd0;

assign buf_V_34_address0 = outpix_cast_fu_969_p1;

assign buf_V_34_d0 = 3'd0;

assign buf_V_35_address0 = outpix_cast_fu_969_p1;

assign buf_V_35_d0 = 3'd0;

assign buf_V_36_address0 = outpix_cast_fu_969_p1;

assign buf_V_36_d0 = 3'd0;

assign buf_V_37_address0 = outpix_cast_fu_969_p1;

assign buf_V_37_d0 = 3'd0;

assign buf_V_38_address0 = outpix_cast_fu_969_p1;

assign buf_V_38_d0 = 3'd0;

assign buf_V_39_address0 = outpix_cast_fu_969_p1;

assign buf_V_39_d0 = 3'd0;

assign buf_V_3_address0 = outpix_cast_fu_969_p1;

assign buf_V_3_d0 = 3'd0;

assign buf_V_40_address0 = outpix_cast_fu_969_p1;

assign buf_V_40_d0 = 3'd0;

assign buf_V_41_address0 = outpix_cast_fu_969_p1;

assign buf_V_41_d0 = 3'd0;

assign buf_V_42_address0 = outpix_cast_fu_969_p1;

assign buf_V_42_d0 = 3'd0;

assign buf_V_43_address0 = outpix_cast_fu_969_p1;

assign buf_V_43_d0 = 3'd0;

assign buf_V_44_address0 = outpix_cast_fu_969_p1;

assign buf_V_44_d0 = 3'd0;

assign buf_V_45_address0 = outpix_cast_fu_969_p1;

assign buf_V_45_d0 = 3'd0;

assign buf_V_46_address0 = outpix_cast_fu_969_p1;

assign buf_V_46_d0 = 3'd0;

assign buf_V_47_address0 = outpix_cast_fu_969_p1;

assign buf_V_47_d0 = 3'd0;

assign buf_V_48_address0 = outpix_cast_fu_969_p1;

assign buf_V_48_d0 = 3'd0;

assign buf_V_49_address0 = outpix_cast_fu_969_p1;

assign buf_V_49_d0 = 3'd0;

assign buf_V_4_address0 = outpix_cast_fu_969_p1;

assign buf_V_4_d0 = 3'd0;

assign buf_V_50_address0 = outpix_cast_fu_969_p1;

assign buf_V_50_d0 = 3'd0;

assign buf_V_51_address0 = outpix_cast_fu_969_p1;

assign buf_V_51_d0 = 3'd0;

assign buf_V_52_address0 = outpix_cast_fu_969_p1;

assign buf_V_52_d0 = 3'd0;

assign buf_V_53_address0 = outpix_cast_fu_969_p1;

assign buf_V_53_d0 = 3'd0;

assign buf_V_54_address0 = outpix_cast_fu_969_p1;

assign buf_V_54_d0 = 3'd0;

assign buf_V_55_address0 = outpix_cast_fu_969_p1;

assign buf_V_55_d0 = 3'd0;

assign buf_V_5_address0 = outpix_cast_fu_969_p1;

assign buf_V_5_d0 = 3'd0;

assign buf_V_6_address0 = outpix_cast_fu_969_p1;

assign buf_V_6_d0 = 3'd0;

assign buf_V_7_address0 = outpix_cast_fu_969_p1;

assign buf_V_7_d0 = 3'd0;

assign buf_V_8_address0 = outpix_cast_fu_969_p1;

assign buf_V_8_d0 = 3'd0;

assign buf_V_9_address0 = outpix_cast_fu_969_p1;

assign buf_V_9_d0 = 3'd0;

assign buf_V_address0 = outpix_cast_fu_969_p1;

assign buf_V_d0 = 3'd0;

assign icmp_ln174_fu_957_p2 = ((ap_sig_allocacmp_outpix_1 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln174_reg_1158_pp0_iter0_reg = icmp_ln174_reg_1158;

assign out_V_TDATA = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{buf_V_55_q0}, {buf_V_54_q0}}, {buf_V_53_q0}}, {buf_V_52_q0}}, {buf_V_51_q0}}, {buf_V_50_q0}}, {buf_V_49_q0}}, {buf_V_48_q0}}, {buf_V_47_q0}}, {buf_V_46_q0}}, {buf_V_45_q0}}, {buf_V_44_q0}}, {buf_V_43_q0}}, {buf_V_42_q0}}, {buf_V_41_q0}}, {buf_V_40_q0}}, {buf_V_39_q0}}, {buf_V_38_q0}}, {buf_V_37_q0}}, {buf_V_36_q0}}, {buf_V_35_q0}}, {buf_V_34_q0}}, {buf_V_33_q0}}, {buf_V_32_q0}}, {buf_V_31_q0}}, {buf_V_30_q0}}, {buf_V_29_q0}}, {buf_V_28_q0}}, {buf_V_27_q0}}, {buf_V_26_q0}}, {buf_V_25_q0}}, {buf_V_24_q0}}, {buf_V_23_q0}}, {buf_V_22_q0}}, {buf_V_21_q0}}, {buf_V_20_q0}}, {buf_V_19_q0}}, {buf_V_18_q0}}, {buf_V_17_q0}}, {buf_V_16_q0}}, {buf_V_15_q0}}, {buf_V_14_q0}}, {buf_V_13_q0}}, {buf_V_12_q0}}, {buf_V_11_q0}}, {buf_V_10_q0}}, {buf_V_9_q0}}, {buf_V_8_q0}}, {buf_V_7_q0}}, {buf_V_6_q0}}, {buf_V_5_q0}}, {buf_V_4_q0}}, {buf_V_3_q0}}, {buf_V_2_q0}}, {buf_V_1_q0}}, {buf_V_q0}};

assign outpix_cast_fu_969_p1 = ap_sig_allocacmp_outpix_1;

endmodule //StreamingMaxPool_hls_4_StreamingMaxPool_Precision_Pipeline_VITIS_LOOP_174_8
