#!/bin/bash 
cd /tmp/finn_dev_root/code_gen_ipgen_StreamingDataWidthConverter_hls_0_quz2zfen
vitis_hls /tmp/finn_dev_root/code_gen_ipgen_StreamingDataWidthConverter_hls_0_quz2zfen/hls_syn_StreamingDataWidthConverter_hls_0.tcl
cd /media/clr/XIlinx/finn
