<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>MVAU_hls_5</name>
      <module_structure>Sequential</module_structure>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>in0_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in0_V</originalName>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>3704819776</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>weights_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>weights_V</originalName>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>543517801</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>936</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_3">
          <Value>
            <Obj>
              <type>1</type>
              <id>3</id>
              <name>out_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out_V</originalName>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>3706319904</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>40</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>103</id>
              <name>_ln37</name>
              <fileName>/tmp/finn_dev_root/code_gen_ipgen_MVAU_hls_5_ol2hz86g/top_MVAU_hls_5.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>37</lineNumber>
              <contextFuncName>MVAU_hls_5</contextFuncName>
              <contextNormFuncName>MVAU_hls_5</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>/tmp/finn_dev_root/code_gen_ipgen_MVAU_hls_5_ol2hz86g</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>/tmp/finn_dev_root/code_gen_ipgen_MVAU_hls_5_ol2hz86g/top_MVAU_hls_5.cpp</first>
                        <second>MVAU_hls_5</second>
                      </first>
                      <second>37</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_Matrix_Vector_Activate_Stream_Batch_fu_212</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>1936290921</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>95</count>
            <item_version>0</item_version>
            <item>107</item>
            <item>108</item>
            <item>109</item>
            <item>110</item>
            <item>111</item>
            <item>112</item>
            <item>113</item>
            <item>114</item>
            <item>115</item>
            <item>116</item>
            <item>117</item>
            <item>118</item>
            <item>119</item>
            <item>120</item>
            <item>121</item>
            <item>122</item>
            <item>123</item>
            <item>124</item>
            <item>125</item>
            <item>126</item>
            <item>127</item>
            <item>128</item>
            <item>129</item>
            <item>130</item>
            <item>131</item>
            <item>132</item>
            <item>133</item>
            <item>134</item>
            <item>135</item>
            <item>136</item>
            <item>137</item>
            <item>138</item>
            <item>139</item>
            <item>140</item>
            <item>141</item>
            <item>142</item>
            <item>143</item>
            <item>144</item>
            <item>145</item>
            <item>146</item>
            <item>147</item>
            <item>148</item>
            <item>149</item>
            <item>150</item>
            <item>151</item>
            <item>152</item>
            <item>153</item>
            <item>154</item>
            <item>155</item>
            <item>156</item>
            <item>157</item>
            <item>158</item>
            <item>159</item>
            <item>160</item>
            <item>161</item>
            <item>162</item>
            <item>163</item>
            <item>164</item>
            <item>165</item>
            <item>166</item>
            <item>167</item>
            <item>168</item>
            <item>169</item>
            <item>170</item>
            <item>171</item>
            <item>172</item>
            <item>173</item>
            <item>174</item>
            <item>175</item>
            <item>176</item>
            <item>177</item>
            <item>178</item>
            <item>179</item>
            <item>180</item>
            <item>181</item>
            <item>182</item>
            <item>183</item>
            <item>184</item>
            <item>185</item>
            <item>186</item>
            <item>187</item>
            <item>188</item>
            <item>189</item>
            <item>190</item>
            <item>191</item>
            <item>192</item>
            <item>193</item>
            <item>194</item>
            <item>195</item>
            <item>196</item>
            <item>197</item>
            <item>198</item>
            <item>199</item>
            <item>200</item>
            <item>201</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>1</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>1</m_isStartOfPath>
          <m_delay>1.58</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>104</id>
              <name>_ln39</name>
              <fileName>/tmp/finn_dev_root/code_gen_ipgen_MVAU_hls_5_ol2hz86g/top_MVAU_hls_5.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>39</lineNumber>
              <contextFuncName>MVAU_hls_5</contextFuncName>
              <contextNormFuncName>MVAU_hls_5</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/tmp/finn_dev_root/code_gen_ipgen_MVAU_hls_5_ol2hz86g</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/tmp/finn_dev_root/code_gen_ipgen_MVAU_hls_5_ol2hz86g/top_MVAU_hls_5.cpp</first>
                        <second>MVAU_hls_5</second>
                      </first>
                      <second>39</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>606403328</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_6">
          <Value>
            <Obj>
              <type>2</type>
              <id>106</id>
              <name>Matrix_Vector_Activate_Stream_Batch</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>3695771360</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:Matrix_Vector_Activate_Stream_Batch&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_7">
          <Obj>
            <type>3</type>
            <id>105</id>
            <name>MVAU_hls_5</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>1330007625</coreId>
            <rtlModuleName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>103</item>
            <item>104</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>95</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_8">
          <id>107</id>
          <edge_type>1</edge_type>
          <source_obj>106</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_9">
          <id>108</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_10">
          <id>109</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_11">
          <id>110</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_12">
          <id>111</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_13">
          <id>112</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_14">
          <id>113</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_15">
          <id>114</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_16">
          <id>115</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_17">
          <id>116</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_18">
          <id>117</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_19">
          <id>118</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_20">
          <id>119</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_21">
          <id>120</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_22">
          <id>121</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>122</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>123</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>124</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>125</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>126</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>127</id>
          <edge_type>1</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>128</id>
          <edge_type>1</edge_type>
          <source_obj>21</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>129</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>130</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>131</id>
          <edge_type>1</edge_type>
          <source_obj>24</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>132</id>
          <edge_type>1</edge_type>
          <source_obj>25</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>133</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>134</id>
          <edge_type>1</edge_type>
          <source_obj>27</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>135</id>
          <edge_type>1</edge_type>
          <source_obj>28</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>136</id>
          <edge_type>1</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>137</id>
          <edge_type>1</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>138</id>
          <edge_type>1</edge_type>
          <source_obj>31</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>139</id>
          <edge_type>1</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>140</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>141</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>142</id>
          <edge_type>1</edge_type>
          <source_obj>35</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>143</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>144</id>
          <edge_type>1</edge_type>
          <source_obj>37</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>145</id>
          <edge_type>1</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>146</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>147</id>
          <edge_type>1</edge_type>
          <source_obj>40</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>148</id>
          <edge_type>1</edge_type>
          <source_obj>41</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>149</id>
          <edge_type>1</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>150</id>
          <edge_type>1</edge_type>
          <source_obj>43</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>151</id>
          <edge_type>1</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>152</id>
          <edge_type>1</edge_type>
          <source_obj>45</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>153</id>
          <edge_type>1</edge_type>
          <source_obj>46</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>154</id>
          <edge_type>1</edge_type>
          <source_obj>47</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>155</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>156</id>
          <edge_type>1</edge_type>
          <source_obj>49</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>157</id>
          <edge_type>1</edge_type>
          <source_obj>50</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>158</id>
          <edge_type>1</edge_type>
          <source_obj>51</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>159</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>160</id>
          <edge_type>1</edge_type>
          <source_obj>53</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>161</id>
          <edge_type>1</edge_type>
          <source_obj>54</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>162</id>
          <edge_type>1</edge_type>
          <source_obj>55</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>163</id>
          <edge_type>1</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>164</id>
          <edge_type>1</edge_type>
          <source_obj>57</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>165</id>
          <edge_type>1</edge_type>
          <source_obj>58</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>166</id>
          <edge_type>1</edge_type>
          <source_obj>59</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>167</id>
          <edge_type>1</edge_type>
          <source_obj>60</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>168</id>
          <edge_type>1</edge_type>
          <source_obj>61</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>169</id>
          <edge_type>1</edge_type>
          <source_obj>62</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>170</id>
          <edge_type>1</edge_type>
          <source_obj>63</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_72">
          <id>171</id>
          <edge_type>1</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_73">
          <id>172</id>
          <edge_type>1</edge_type>
          <source_obj>65</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_74">
          <id>173</id>
          <edge_type>1</edge_type>
          <source_obj>66</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_75">
          <id>174</id>
          <edge_type>1</edge_type>
          <source_obj>67</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_76">
          <id>175</id>
          <edge_type>1</edge_type>
          <source_obj>68</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_77">
          <id>176</id>
          <edge_type>1</edge_type>
          <source_obj>69</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_78">
          <id>177</id>
          <edge_type>1</edge_type>
          <source_obj>70</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_79">
          <id>178</id>
          <edge_type>1</edge_type>
          <source_obj>71</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_80">
          <id>179</id>
          <edge_type>1</edge_type>
          <source_obj>72</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_81">
          <id>180</id>
          <edge_type>1</edge_type>
          <source_obj>73</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_82">
          <id>181</id>
          <edge_type>1</edge_type>
          <source_obj>74</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_83">
          <id>182</id>
          <edge_type>1</edge_type>
          <source_obj>75</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_84">
          <id>183</id>
          <edge_type>1</edge_type>
          <source_obj>76</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_85">
          <id>184</id>
          <edge_type>1</edge_type>
          <source_obj>77</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_86">
          <id>185</id>
          <edge_type>1</edge_type>
          <source_obj>78</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_87">
          <id>186</id>
          <edge_type>1</edge_type>
          <source_obj>79</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_88">
          <id>187</id>
          <edge_type>1</edge_type>
          <source_obj>80</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_89">
          <id>188</id>
          <edge_type>1</edge_type>
          <source_obj>81</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_90">
          <id>189</id>
          <edge_type>1</edge_type>
          <source_obj>82</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_91">
          <id>190</id>
          <edge_type>1</edge_type>
          <source_obj>83</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_92">
          <id>191</id>
          <edge_type>1</edge_type>
          <source_obj>84</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_93">
          <id>192</id>
          <edge_type>1</edge_type>
          <source_obj>85</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_94">
          <id>193</id>
          <edge_type>1</edge_type>
          <source_obj>86</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_95">
          <id>194</id>
          <edge_type>1</edge_type>
          <source_obj>87</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_96">
          <id>195</id>
          <edge_type>1</edge_type>
          <source_obj>88</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_97">
          <id>196</id>
          <edge_type>1</edge_type>
          <source_obj>89</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_98">
          <id>197</id>
          <edge_type>1</edge_type>
          <source_obj>90</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_99">
          <id>198</id>
          <edge_type>1</edge_type>
          <source_obj>91</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_100">
          <id>199</id>
          <edge_type>1</edge_type>
          <source_obj>92</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_101">
          <id>200</id>
          <edge_type>1</edge_type>
          <source_obj>93</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_102">
          <id>201</id>
          <edge_type>1</edge_type>
          <source_obj>94</source_obj>
          <sink_obj>103</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_103">
        <mId>1</mId>
        <mTag>MVAU_hls_5</mTag>
        <mNormTag>MVAU_hls_5</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>105</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>281227</mMinLatency>
        <mMaxLatency>281227</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_104">
      <states class_id="25" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_105">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_106">
          <id>2</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_107">
              <id>103</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_108">
          <id>3</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_109">
              <id>103</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_110">
          <id>4</id>
          <operations>
            <count>9</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_111">
              <id>95</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_112">
              <id>96</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_113">
              <id>97</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_114">
              <id>98</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_115">
              <id>99</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_116">
              <id>100</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_117">
              <id>101</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_118">
              <id>102</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_119">
              <id>104</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_120">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_121">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_122">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="34" tracking_level="1" version="0" object_id="_123">
      <dp_component_resource class_id="35" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>grp_Matrix_Vector_Activate_Stream_Batch_fu_212 (Matrix_Vector_Activate_Stream_Batch)</first>
          <second class_id="37" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="0" version="0">
              <first>BRAM</first>
              <second>0</second>
            </item>
            <item>
              <first>DSP</first>
              <second>78</second>
            </item>
            <item>
              <first>FF</first>
              <second>8415</second>
            </item>
            <item>
              <first>LUT</first>
              <second>5715</second>
            </item>
          </second>
        </item>
        <item>
          <first>regslice_both_in0_V_U (MVAU_hls_5_regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_V_U (MVAU_hls_5_regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_weights_V_U (MVAU_hls_5_regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>grp_Matrix_Vector_Activate_Stream_Batch_fu_212_out_V_TREADY ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>5</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>5</second>
            </item>
            <item>
              <first>LUT</first>
              <second>25</second>
            </item>
          </second>
        </item>
        <item>
          <first>in0_V_TREADY_int_regslice</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>weights_V_TREADY_int_regslice</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>4</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_Matrix_Vector_Activate_Stream_Batch_fu_212_ap_start_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>4</count>
        <item_version>0</item_version>
        <item>
          <first>grp_Matrix_Vector_Activate_Stream_Batch_fu_212</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in0_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_weights_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="39" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="0" version="0">
          <first>grp_Matrix_Vector_Activate_Stream_Batch_fu_212 (Matrix_Vector_Activate_Stream_Batch)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>103</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="41" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="42" tracking_level="0" version="0">
        <first>103</first>
        <second class_id="43" tracking_level="0" version="0">
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>104</first>
        <second>
          <first>3</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="44" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>105</first>
        <second class_id="46" tracking_level="0" version="0">
          <first>0</first>
          <second>3</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="47" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="48" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="49" tracking_level="0" version="0">
        <first>212</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>103</item>
          <item>103</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="51" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>grp_Matrix_Vector_Activate_Stream_Batch_fu_212</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>103</item>
          <item>103</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="53" tracking_level="0" version="0">
      <count>91</count>
      <item_version>0</item_version>
      <item class_id="54" tracking_level="0" version="0">
        <first class_id="55" tracking_level="0" version="0">
          <first>p_ZL7threshs_0_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_0_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_0_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_0_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_0_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_0_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_0_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_10_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_11_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_12_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_1_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_2_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_3_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_4_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_5_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_6_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_7_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_8_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
      <item>
        <first>
          <first>p_ZL7threshs_9_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>103</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="56" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="57" tracking_level="0" version="0">
        <first>in0_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>103</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>103</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>weights_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>103</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>103</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
    </node2core>
  </syndb>
</boost_serialization>
